README.md

Add example queries to README, fixes #21 and #24

---

lib/create-space-api.js
lib/entities/content-type.js
lib/entities/editor-interface.js
lib/entities/index.js
package.json
test/integration/content-type-integration.js
test/integration/integration-tests.js
test/unit/create-space-api-test.js
test/unit/entities/content-type-test.js
test/unit/entities/editor-interface-test.js
test/unit/mocks/entities.js

Add Editor Interface Support 

---

README.md

@Khaledgarbaya Nothing major :)

Some small typo fixes and tweaks

---

package.json

feat(sdk-core): update the sdk core dependency

---

esdoc.json
index.js
lib/contentful-management.js
lib/create-contentful-api.js
lib/create-space-api.js
lib/entities/api-key.js
lib/entities/asset.js
lib/entities/content-type.js
lib/entities/editor-interface.js
lib/entities/entry.js
lib/entities/locale.js
lib/entities/role.js
lib/entities/space-membership.js
lib/entities/space.js
lib/error-handler.js
lib/instance-actions.js
package.json
test/runner-browser.js

It is time to fix the documentation issue for all of the SDKs, I am starting first with contentful-management. I decided to move away from jsdoc as it become a bit complicated to maintain and use esdoc instead.
The new template will look much much nicer, it does provide search functionality, links between Classes and every class will have a more detailed example about all of its functionality.
Preview :

Docs revisited

---

lib/contentful-management.js
lib/entities/space.js
package.json
test/unit/contentful-management-test.js
test/unit/entities/space-test.js
version.js
yarn.lock

Some changes are required for to be able to use the new rate limiting introduced [here](https://github.com/contentful/contentful-sdk-core/pull/13)

feat(rateLimit): Use the new ratelimit logic

---

lib/contentful-management.js
yarn.lock

Remove leftover params `maxRetries` and `rateLimitPeriod`.

refactor: Remove leftovers params

---

index.js
lib/contentful-management.js
package.json
test/unit/contentful-management-test.js
version.js

This PR fixes the export issue in the umd build for the browser

fix(build): fix umb build for browser

---

lib/create-contentful-api.js
lib/entities/index.js
lib/entities/organization.js
test/integration/integration-tests.js
test/unit/create-contentful-api-test.js
test/unit/entities/organization-test.js
test/unit/mocks/entities.js
test/unit/mocks/http.js

Implements new organizations endpoint

feat(organizations): implement new organizations endpoint

---

lib/error-handler.js

instead of `ACCESS_TOKEN` we show the last 5 characters of the token and pre-pend `...`

feat(errHandler): make token obfuscation more obvious

---

README.md
lib/contentful-management.js
package.json
yarn.lock

* Adds `retryOnError` flag with default to true
* Adds configuration section to the readme
* Aligns the readme to match other SDK's format

feat(error-retry): add flag to disable retry on error and align readme

---

.babelrc
README.md
package.json

* fixes babel config + updates babel related dependencies
* upgrades sdk-core to support custom log handling

feat(logging): add custom log handling function

---

lib/create-space-api.js
lib/entities/content-type.js
lib/entities/entry.js
lib/entities/index.js
lib/entities/snapshot.js
test/integration/content-type-integration.js
test/integration/entry-integration.js
test/integration/webhook-integration.js
test/unit/create-space-api-test.js
test/unit/entities/content-type-test.js
test/unit/entities/entry-test.js
test/unit/mocks/entities.js
test/unit/test-creators/instance-entity-methods.js
version.js

This PR adds support for the snapshots endpoints

feat(entities): Add Snapshots endpoint

---

package.json
test/e2e/index.js
test/e2e/server.js

tests the `.browser.min.js` in firefox  and the `.legacy.min.js` in IE 11

end to end tests

---

README.md

docs(README): fix unpkg url and add non-node environment hint

---

package.json

based on https://github.com/contentful/contentful.js/pull/195

fix(npm): Remove git dependancy for package axios

---

lib/entities/personal-access-token.js

fix: fix personalAccessToken revoke doc

---

lib/create-space-api.js

Pass query params for pagination, skip and limit

feat(space_memberships): Pass query parameters

---

lib/create-space-api.js
lib/entities/environment.js
lib/entities/preview-api-key.js
package.json
test/unit/entities/environment-test.js
test/unit/entities/preview-api-key-test.js
test/unit/mocks/entities.js

This PR fixes the environment direct file upload and preview api key

fix: fix environment upload

---

lib/create-contentful-api.js

good catch @zeusdeux 
* adds missing 4 functions to the menu
* adds example code and more detailed docs for these 4 aswell

docs(client): add correct membership to functions

---

lib/contentful-management.js

docs(contentful-management): document timeout param for createClient

---

package.json
test/integration/environment-integration.js

this will include a fix to the httpagent in sdk-core

fix(sdk-core): bump sdk-core to 6.3.1

---

lib/create-space-api.js
lib/entities/environment-alias.js
lib/entities/index.js
lib/instance-actions.js
package.json
test/integration/environment-alias-integration.js
test/integration/integration-tests.js
test/unit/create-space-api-test.js
test/unit/entities/environment-alias-test.js
test/unit/mocks/entities.js
test/unit/test-creators/instance-entity-methods.js

Preparation for the eventual release. 
Of course tests will still fail until that point.

Environment alias release

---

lib/create-organization-api.js
lib/entities/index.js
lib/entities/organization-membership.js
lib/entities/organization.js
package.json
test/integration/integration-tests.js
test/integration/organization-membership-integration.js
test/unit/create-organization-api-test.js
test/unit/entities/organization-membership-test.js
test/unit/entities/organization-test.js
test/unit/mocks/entities.js

As a part of the following task https://contentful.atlassian.net/browse/HEJO-1109 we would like to add `/organizations/{orgId}/organization_memberships` to the SDK.
I would like to get your feedback at this point to be sure that we are going in the right direction. Integration tests are still missing, but before I go to far I would like to be sure that this is the right approach. Tell me WDYT! Thx a lot for your feedback 🙇‍♀️

Organization membership endpoint

---

lib/create-organization-api.js

Final part of the https://contentful.atlassian.net/browse/HEJO-1140

Remove alpha header for organization space memberships endpoints

---

lib/create-organization-api.js
lib/entities/organization-membership.js

Just a small update for documentation, to make sure is not misleading.

Fix documentation for getOrganization

---

lib/create-organization-api.js
lib/entities/index.js
lib/entities/team.js
test/integration/integration-tests.js
test/integration/team-integration.js
test/unit/create-organization-api-test.js
test/unit/entities/team-test.js
test/unit/mocks/entities.js
typings/organization.d.ts
typings/team.d.ts

Added /organization/orgId/teams endpoints: createTeam, getTeam (with update and delete), getTeams.

feat(organizationTeams): added organization teams endpoints

---

lib/create-space-api.js
lib/entities/index.js
lib/entities/team-space-membership.js
package.json
test/integration/integration-tests.js
test/integration/team-space-membership-integration.js
test/unit/create-space-api-test.js
test/unit/entities/team-space-membership-test.js
test/unit/mocks/entities.js
typings/space.d.ts
typings/teamSpaceMembership.d.ts

Adding support for teamSpaceMemberships - part of the https://contentful.atlassian.net/browse/HEJO-1148

feat(teamSpaceMemberships): Team space memberships endpoints

---

lib/create-organization-api.js
test/integration/integration-tests.js
test/integration/org-team-space-membership-integration.js
test/unit/create-organization-api-test.js
test/unit/mocks/entities.js
typings/organization.d.ts
typings/teamSpaceMembership.d.ts

Add support for GET requests for Team Space Membership at the organization level

feat(teamSpaceMembership): implement org level team space memberships

---

lib/create-organization-api.js
typings/organization.d.ts
typings/space.d.ts

small docs and typings fix to solve github issues

fix(typings): createTeamMemberships and createTeamSpaceMemberships typings

---

typings/index.d.ts

Fixes incorrect export from `index` typescript definition

fix: correct createClient export

---

lib/entities/role.ts
typings/generated/entities/role.d.ts

I believe these are the correct typings for space roles.
Should fix issue https://github.com/contentful/contentful-management.js/issues/363 and potentially https://github.com/contentful/contentful-management.js/issues/360

fix: role typings

---

lib/entities/webhook.ts

fix: incorrect webhook types

---

lib/create-contentful-api.ts
lib/create-environment-api.ts
lib/create-space-api.ts
lib/entities/content-type.ts
lib/entities/locale.ts
lib/entities/personal-access-token.ts

fix: improve create method typings

---

README.md
lib/create-contentful-api.ts
lib/create-environment-api.ts
lib/entities/content-type.ts
lib/entities/personal-access-token.ts
lib/entities/webhook.ts

Merges latest changes from `master` to an experimental branch

feat: backport changes from master to experimental

---

.circleci/config.yml

(cherry picked from commit 174a46931c38bb434e8550c4f12cbb03215fa439)

build: release only in main branches

---

lib/plain/endpoints/content-type.ts

Do not rely on async/await for now.

fix: do not use async/await directly

---

lib/entities/tag.ts
test/integration/tag-integration.js

fix(tags): fix update tag path

---

lib/entities/environment-alias.ts

Closes https://github.com/contentful/contentful-management.js/issues/406

fix: incorrect types for environment aliases

---

lib/create-environment-api.ts
lib/entities/editor-interface.ts
lib/plain/endpoints/editor-interface.ts
lib/plain/plain-client.ts
test/unit/create-environment-api-test.js
test/unit/mocks/entities.js

* Exposes new method to the main client
* Exposes new method to the flat client
* Refactored the code to used `endpoints` in the main client implementation.

feat: exposes new editor_interface collection endpoint

---

PROGRESS.md

To the track the progress of porting existing methods to a flat API

chore: create a progress document

---

lib/create-space-api.ts

Context: https://contentful.atlassian.net/browse/SDK-1172

fix: update environment warning

---

.gitignore
package-lock.json
package.json

chore(lock-file): add

---

.gitignore
PROGRESS.md
lib/create-space-api.ts
lib/entities/editor-interface.ts
lib/entities/environment-alias.ts
lib/entities/index.ts
package-lock.json
package.json
test/integration/environment-alias-integration.js
test/integration/integration-tests.js
test/integration/tag-integration.js
test/unit/create-space-api-test.js

Merges the latest changes from the master branch into an experimental branch

chore: merge master to experimental

---

lib/create-cma-http-client.ts
lib/plain/plain-client.ts

To measure adoption rate in the long run.

chore: distinction between plain and older client

---

lib/entities/locale.ts

Closes https://github.com/contentful/contentful-management.js/issues/517

fix: correct fallbackCode type for Locale

---

lib/entities/role.ts

Closes https://github.com/contentful/contentful-management.js/issues/461

fix: allow optional constraint type

---

lib/create-contentful-api.ts

fix: correctly pass params to plain client for getSpaces

---

README.md

Closes https://github.com/contentful/contentful-management.js/issues/579

chore: add regenerator-runtime to browser example

---

lib/entities/locale.ts
lib/entities/space-membership.ts

Fixes https://github.com/contentful/contentful-management.js/issues/576

fix: proper types for create space-membership and create locale methods

---

.dependabot/config.yml
package-lock.json
package.json

Solves problem with publishing and releasing from the main branch.

fix: dowgrade typedoc version

---

lib/create-environment-api.ts
lib/entities/tag.ts
lib/plain/endpoints/tag.ts
test/integration/entry-integration.js
test/integration/tag-integration.js
test/unit/mocks/entities.js

Allow creation of "public" tags with a default fallback to "private"

feat(tags): create with visibility

---

lib/entities/app-definition.ts
lib/export-types.ts

Exports some more types that I want to use elsewhere 

feat: export members of AppLocation enum

---

lib/entities/app-definition.ts
lib/export-types.ts

exporting a type for use externally

feat: [] export navigation item type

---

lib/adapters/REST/endpoints/index.ts
test/integration/asset-key-integration.js

fix: add missing AssetKey endpoints [EXT-2525]

---

test/integration/asset-integration.js
test/integration/tag-integration.js

re-activate tests for asset processing

fix(integration-tests): assets

---

test/integration/entry-integration.js

Due to changed set of data on the test space, we have to adjust our integration test to match count

fix(tests): adjust expected entry count

---

package.json
test/integration/entry-integration.js

Respect the newly added content type `kangaroo` in our test space

fix(integration-test): add new content type

---

lib/adapters/REST/endpoints/tag.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/tag.ts

for unclear reasons, a version with invalid types got released. This PR fixes the types (again)

fix(types): tag

---

lib/create-environment-api.ts

Cast `wrapEntryCollection` with the proper types

fix: getEntryReferences types

---

lib/export-types.ts

fix: export TagVisibility

---

test/integration/space-team-integration.js

feat(scheduled-actions-update): attempt to auto trigger release

---

lib/entities/role.ts

feat(roles): add tags to permissions type

---

lib/entities/app-definition.ts

feat: Add shared to App Definition [EXT-2709]

---

lib/adapters/REST/endpoints/content-type.ts

GIve more flexibility when talking to content-types.

feat: ability to add headers to content-type methods

---

lib/adapters/REST/endpoints/api-key.ts
lib/adapters/REST/endpoints/team-space-membership.ts
lib/common-utils.ts
lib/create-contentful-api.ts
lib/create-organization-api.ts
lib/create-space-api.ts
package-lock.json
package.json
test/integration/asset-integration.js
test/unit/adapters/REST/endpoints/asset-test.js

Ensure contentful/contentful-sdk-core#239 is being used.

fix: contentful-sdk-core v6.10.4

---

lib/create-space-api.ts
lib/entities/scheduled-action.ts

Inspired by #900 but as the checks are not being properly run on that PR, and the author is not responding, I decided to do the same here
Aligns the data structure in example comments to match the actual data structure
Makes the examples more useful, saves the headache of figuring it out

chore: fix example data structures in comments

---

lib/adapters/REST/endpoints/workflow-definition.ts
lib/common-types.ts
lib/entities/workflow-definition.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts

Add support for the workflow definition query feature.
Allow querying workflows in the environment, support skip and limit.

feat: add support for wf definition query []

---

lib/entities/release.ts

Add `order` to release query options.

chore: update release query options [SPA-507]

---

lib/adapters/REST/endpoints/index.ts
lib/adapters/REST/endpoints/workflow.ts
lib/common-types.ts
lib/entities/workflow.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/workflow.ts
test/unit/entities/workflow.ts
test/unit/mocks/entities.js

Adding a new entity called Workflows under the alpha feature.
Adding typings and methods:
- create
- update
- query
- delete
- complete
No documentation update for alpha features.

feat: add workflow entity

---

lib/adapters/REST/endpoints/app-action.ts
lib/adapters/REST/endpoints/index.ts
lib/common-types.ts
lib/create-organization-api.ts
lib/entities/app-action.ts
lib/entities/index.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/app-action-integration.ts
test/unit/create-organization-api-test.js
test/unit/mocks/entities.js

feat: [EXT-3440] add app actions

---

lib/adapters/REST/endpoints/app-action-call.ts
lib/adapters/REST/endpoints/index.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/app-action-call.ts
lib/entities/index.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/unit/create-environment-api-test.js
test/unit/mocks/entities.js

feat: [EXT-3440] add app action call entity

---

lib/entities/workflow-definition.ts
package-lock.json

Update workflow step action types so that users can create actions via the sdk

feat: update workflow step action types [HOMER-612]

---

.eslintrc.js
.prettierrc
lib/adapters/REST/endpoints/team-space-membership.ts
package-lock.json
package.json

Update prettier and related packages

chore: Update prettier

---

lib/entities/app-definition.ts

- Add a new entry list app location

feat: new entry list app location

---

.circleci/config.yml

chore: install node from nvmrc before release []

---

lib/entities/app-action.ts
test/integration/app-action-integration.ts

Updating Custom app action types to match API

fix(ActionCategories): fix app action category types [EXT-3722]

---

lib/adapters/REST/endpoints/workflow.ts

Fix: completing workflows, pass the 3rd parameter as null for the request body so headers are properly passed.

fix: completing workflows

---

lib/entities/workflow-definition.ts

Add new flowType property to the WorkflowDefinition entity.

feat: add flow type [HOMER-1038]

---

lib/entities/workflow-definition.ts

- Extending Workflow Definition Type to include a different type of WorkflowStepPermission (WorkflowPermission).
- This new type of permission determined if a user can change the current step of a workflow

feat: extended WorkflowStepPermissionType [HOMER-1068]

---

lib/entities/app-definition.ts

- Freeze Entry List location for now
Related PR: https://github.com/contentful/contentful-management.js/pull/1235

refactor: cleanup Entry List location logic [BAU-910]

---

lib/entities/app-action.ts

fix: categories renamed in app action category type  [EXT-3783]

---

.contentful/vault-secrets.yaml

Init vault to use with circleci
1st of the two PRs needed for this migration.

feat: add vault config [SDK-2275]

---

.circleci/config.yml
.contentful/vault-secrets.yaml
.github/workflows/dependabot-approve-and-request-merge.yml

Modify circleci to use vault
Needs [this PR](https://github.com/contentful/contentful-management.js/pull/1498) to be merged before merging this one

feat: use vault config in circleci [SDK-2275]

---

test/helpers.js
test/integration/environment-template-integration.ts
test/mocha-global.js
test/unit/create-contentful-api-test.js

Adds integration tests for the environments template api

Monet 872 content model template integration tests

---

lib/entities/app-action.ts

Allow app action to have description

feat(AppAction): add app action description [EXT-3920]

---

lib/entities/content-type-fields.ts

Support custom error message for Validators
Currently it's not possible to add a custom error message for the validators. With this PR it is now possible.

Support custom error message for Validators

---

lib/entities/content-type-fields.ts

Reverts contentful/contentful-management.js#1519 to ensure correct commit message in order to unblock release

Revert "Support custom error message for Validators"

---

lib/entities/content-type-fields.ts

Based on https://github.com/contentful/contentful-management.js/pull/1519
PR is here to create correct commit message --> release handling

feat(validation): support custom validation error message

---

lib/entities/environment-template-installation.ts
lib/entities/environment-template.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts

Add environment templates to plain client
This PR extents the CMA plain client with environments templates

feat: add environment templates to plain client [MONET-525]

---

lib/entities/app-action.ts

Add app action type to app actions as the api will return it in the near future.

feat: add app action type [SDK-2388]

---

lib/entities/comment.ts
lib/entities/workflows-changelog-entry.ts
lib/export-types.ts

Expose workflow in the changelog.

feat: expose workflow in changelog [HOMER-1505]

---

.circleci/config.yml
test/defaults.ts
test/integration/entry-integration.js
test/utils.ts

We had some accidentally created entities in our test space that caused integration tests to fail. 
I also had to disable the cross-space entry tests, for now, to unblock us from further merging.

chore: fix integration tests

---

test/integration/entry-integration.js

fixing the cross space references integration tests

fix: cleaning x-space related tests

---

lib/entities/comment.ts

Add a `ref` property to the comment `parentEntity.sys` object.

feat: add ref to the comment parent sys [HOMER-1912]

---

lib/export-types.ts

Properly exposing `PlainClientAPI` type.

feat: [EXT-3599] Expose plain client type

---

lib/common-types.ts
lib/entities/delivery-function.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts

Contentful will soon support a new entity called DeliveryFunction. This PR adds typings for this entity.

feat: add delivery function entity and types [MONET-1417]

---

lib/export-types.ts

Export `DeliveryFunctionProps` type.
Read more about in a related PR: https://github.com/contentful/contentful-management.js/pull/1941

feat: export DeliveryFunctionProps type [MONET-1417]

---

lib/entities/content-type-fields.ts
package-lock.json
package.json

This PR extends the list of validation types with new Rich Text nodes.

feat: Add more validation types for Rich Text nodes

---

lib/adapters/REST/endpoints/upload.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/upload.ts
lib/plain/common-types.ts
test/integration/asset-integration.js
test/integration/webhook-integration.js
test/unit/adapters/REST/endpoints/upload-test.js

Reverts contentful/contentful-management.js#2030

fix: revert "update createUpload to accept environment id in its params [INTEG-1492]"

---

lib/entities/comment.ts
lib/plain/plain-client-test.ts

* We update the Mention type to enable team mentions in comments

feat: extends mention type [HOMER-2615]

---

lib/entities/content-type-fields.ts
lib/entities/field-type.ts

Extend `ContentTypeAllowedResources ` type to allow adding external resources

feat: support external resource links [DANTE-1298]

---

lib/entities/ui-config.ts

Introduces ui-config and user-ui-config with new property `contentTypeIds` that enables storing multiple content type ids on a view.

feat: enhance views of ui-config with new contentTypeIds property [HOMER-2635]

---

lib/common-types.ts
lib/entities/function.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts

- This change aligns the code base with the latest naming conventions.

fix: renames delivery function to function [MONET-1720]

---

lib/plain/common-types.ts
lib/plain/entities/upload.ts

feat: PlainClient docs - upload [EXT-4964]

---

lib/plain/common-types.ts
lib/plain/entities/user.ts

feat: PlainClient docs - user [EXT-4960]

---

lib/plain/common-types.ts
lib/plain/entities/organization.ts

add TSDocs for organization methods on the plain client

docs: add TSDocs for the organization entity on the plain client interface

---

lib/entities/comment.ts
lib/plain/common-types.ts
lib/plain/entities/app-installation.ts
lib/plain/entities/comment.ts
lib/plain/plain-client-test.ts

docs: PlainClient docs - comment [EXT-4926]

---

test/integration/comment-integration.ts

Tests are not passing right now, this typo should be the reason. Works on my machine, lets see what CircleCI says :)

test(integration): fix comment test structure

---

lib/plain/common-types.ts
lib/plain/entities/role.ts

add TSDocs for roles on the plain client interface

docs: PlainClient docs - role [EXT-4925]

---

.github/CODEOWNERS

Un-own package files for dependabot PRs to self approve and merge

chore: unown package files []

---

lib/plain/common-types.ts
lib/plain/entities/usage.ts

feat: Plain client docs - usage [EXT-4956]

---

lib/plain/entities/upload.ts

fix: fixing example [EXT-00]

---

README.md
test/integration/app-access-token-integration.js
test/integration/app-action-integration.ts
test/integration/app-bundle-integration.js
test/integration/app-definition-integration.js

Updates the README to promote the plain client version over the legacy waterfall client

docs: promote the plain client interface as the default

---

.contentful/vault-secrets.yaml

feat: github migration [EXT-5015]

---

.circleci/config.yml
package-lock.json
package.json

Bumps contentful-sdk-core, and bumps axios to allow versions `1.7.x` to enable support for the new axios `fetch` adapter.

feat: support axios 'fetch' adapter

---

lib/entities/workflows-changelog-entry.ts

We introduce a new query param in the workflows changelog query endpoint

feat: added new query param to workflow changelog query options [CFISO-1734]

---

package-lock.json
package.json
patches/axios+1.7.4.patch

The axios fetch adapter needs this patch to work on Cloudflare workers
see https://github.com/axios/axios/pull/6547

fix: patch axios to include fetch adapter fix [EXT-5371]

---

package-lock.json
package.json

Updates vulnerable dependencies. There are more, but they require also code changes.

fix(deps): group update vulnerable dependencies [NONE]

---

test/integration/taxonomy-integration.ts

Re-activate tests after fixing the problem on the service level

test: re-enable taxonomy-integration.ts tests

---

lib/entities/app-action.ts
lib/export-types.ts

Adds function-invocation type to type field for app action
Do not merge until https://github.com/contentful/extensibility-api/pull/5082 is in

feat: adds function-invocation to app action type [EXT-5324]

---

lib/plain/entities/resource-provider.ts
lib/plain/entities/resource-type.ts
lib/plain/entities/resource.ts

This PR updates the inline comments and examples for NER entities, to get them in sync with examples in the CMA documentation (introduced in this [PR](https://github.com/contentful/doc-app/pull/3257)).
https://contentful.atlassian.net/browse/DANTE-1803

chore: update jsdoc for NER entities [DANTE-1803]

---

lib/common-types.ts
lib/entities/access-token.ts
lib/entities/organization.ts
lib/entities/personal-access-token.ts
lib/export-types.ts

Types removed in #2375 constitute a breaking change. I suggest we add them back and deprecate instead.

fix: add back and deprecate removed types []

---

lib/entities/bulk-action.ts
lib/entities/resource-type.ts
package-lock.json
package.json
test/unit/mocks/entities.ts

Bumps contentful-sdk-core to include this fix https://github.com/contentful/contentful-sdk-core/pull/526

fix: bump contentful-sdk-core to ensure httpsAgent isn't copied [EXT-5676]

---

lib/adapters/REST/rest-adapter.ts

Followup to https://github.com/contentful/contentful-sdk-core/pull/526

fix: don't copy httpAgent/httpsAgent [EXT-5676]

---

.husky/pre-commit
package-lock.json
package.json

Hey there, as part of the modernization for #2334, I migrated to latest husky.

Migrate to husky v9

---

lib/common-types.ts

`sys.fieldStatus` should be an optional property.

fix: [] Make `fieldStatus` optional param

---

lib/entities/ui-config.ts

Adding typings for ui config
So that we can correctly type in consuming repos

fix: adding typings for ui_config []

---

.circleci/config.yml

Fixes global json install in circleci - See https://stackoverflow.com/questions/50915469/simple-circleci-2-0-configuration-fails-for-global-npm-package-installation

chore: install json globally correctly in ci [EXT-00]

---

package-lock.json
package.json

fix: bump axios [ZEND-6126]

---

lib/adapters/REST/endpoints/ai-action-invocation.ts
lib/adapters/REST/endpoints/ai-action.ts
lib/adapters/REST/endpoints/index.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/create-space-api.ts
lib/entities/ai-action-invocation.ts
lib/entities/ai-action.ts
lib/entities/index.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/entities/ai-action-invocation.ts
lib/plain/entities/ai-action.ts
lib/plain/plain-client.ts
test/integration/ai-action-integration.test.ts
test/integration/ai-action-invocation-integration.test.ts
test/unit/create-environment-api.test.ts
test/unit/create-space-api.test.ts
test/unit/entities/ai-action-invocation.test.ts
test/unit/entities/ai-action.test.ts
test/unit/mocks/entities.ts

Add AI action and AI action invocation entities and endpoints.
I built the SDK locally and used the plain client as well as the space/environment clients to test all the AI action operations.

feat: add ai action and ai action invocation [BBEE-1041]

---

lib/contentful-management.ts

feat: export ClientOptions type [EXT-6303]

---

.github/CODEOWNERS

We recently renamed our team in work day and that finally synced in github.
team-tundra -> team-extensibility

chore: rename team-tundra -> team-extensibility [EXT-6372]

---

test/integration/environment-template-integration.test.ts
test/integration/taxonomy-integration.test.ts

Ticket: https://contentful.atlassian.net/browse/GROOT-1871
Updating taxonomy tests after failing.

test: Taxonomy tests are failing after adding conceptScheme on concepts.

---

.github/CODEOWNERS
lib/adapters/REST/endpoints/concept.ts
package-lock.json
package.json
test/integration/environment-template-integration.test.ts
test/integration/taxonomy-integration.test.ts
test/output-integration/browser/package-lock.json

Bump `contentful-sdk-core` to new beta release for testing

fix: bump contentful-sdk-core to new beta [DX-4]

---

lib/adapters/REST/endpoints/release-entry.ts
lib/common-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/releasev2-integration.test.ts

Adds release.entry.update method

feat: add release.entry.update method [DX-206]

---

test/integration/environment-template-integration.test.ts
test/integration/taxonomy-integration.test.ts

JIRA: [DX-268](https://contentful.atlassian.net/browse/DX-268)
Update integration tests:
- Remove skip from environment template tests
- Update taxonomy tests to account for new TaxonomyConcept item below:
```
sys: {
id: 'testConceptDoNotDelete',
type: 'TaxonomyConcept',
createdAt: '2025-07-30T16:23:43.736Z',
updatedAt: '2025-07-30T16:23:43.736Z',
organization: [Object],
createdBy: [Object],
updatedBy: [Object],
version: 1
},
uri: null,
notations: [],
conceptSchemes: [],
broader: [],
related: [],
prefLabel: { 'en-US': 'test-concept-do-not-delete' },
altLabels: { 'en-US': [] },
hiddenLabels: { 'en-US': [] },
note: { 'en-US': '' },
changeNote: null,
definition: { 'en-US': '' },
editorialNote: { 'en-US': '' },
example: { 'en-US': '' },
historyNote: { 'en-US': '' },
scopeNote: { 'en-US': '' } …
```

chore: unskip environment template tests and update taxonomy tests

---

lib/common-types.ts

Align with new API capability to filter template collections by field `forTemplatedSpaces`

feat(environment-templates): add collection filter forTemplatedSpaces [FUS-943]

---

test/integration/app-action-call-structured-integration.test.ts

Follow up to #2766, updating an integration test so that we access the status property from within the sys property.

test: update app action structured integration test []
