.travis.yml
example/clone-space.js
index.js
lib/backoff.js
lib/rate-limit.js
lib/wait.js
package.json
test/integration/asset-test.js
test/integration/content-type-test.js
test/integration/entry-test.js
test/integration/space-test.js
test/unit/backoff-test.js
test/unit/rate-limit-test.js

Function declarations inside blocks is an error in strict mode. Certain versions of V8 actually notice this and throw an error.
/cc @elblivion

[fixed] Strict mode error

---

lib/entities/asset.js

The bug is that after the first setTimeout both parameters are reset to their default values (5 &
500) because they are not passed further down the setTimeout chain.
closes #64

fix(asset): Pass processingCheckWait and processingCheckWait to the next call

---

lib/entities/asset.js
lib/entities/entry.js

Because the docs at https://contentful.github.io/contentful-management.js/contentful-management/1.3.0/typedef/index.html#static-typedef-Entry mention methods that do not exist: `unArchive` and `unPublish`

Use the real method names for unpublish and unarchive in jsdoc

---

lib/contentful-management.js
lib/entities/asset.js
package.json
test/unit/contentful-management-test.js

The new sdk-core version which is [here](https://github.com/contentful/contentful-sdk-core/pull/14) will the remove the export of the ratelimit function as it will be inside the `creaHttpClient` so no need to use outside

feat(rateLimit): Adapt to the new ratelimit api

---

webpack.config.js

the library name in the browser was `contentful-management` but it should be `contentfulManagement` for easy access, this is not a breaking change.

fix(build): fix umd filename

---

lib/create-space-api.js
test/unit/create-space-api-test.js

ContentType for createUpload was previously hardcoded to
applicaion/octet-stream
This fix uses the contentType parameter for uploading a file
Closes #104

fix(createUpload): Setting ContentType

---

package-lock.json
package.json

Axios was assuming always that the proxy protocol is the same as the URL it is requesting. This a problem when you use a http proxy when requesting data from https endpoint.
This is a temporary fix until axios maintainer merges this [PR](https://github.com/mzabriskie/axios/pull/959)

fix(axios): fix proxy

---

lib/instance-actions.js

This is actually a bugfix but marked as feature to avoid issues with semantic-release. (I accidentally released the beta version as 3.9.3 which would now collide with the bugfix. I'll push further beta's with as 4.0 so this won't happen again)

feat(isUpdated): now returns boolean false instead of undefined

---

lib/create-contentful-api.js
lib/entities/index.js
lib/entities/user.js
package.json
test/integration/integration-tests.js
test/unit/create-contentful-api-test.js
test/unit/entities/user-test.js
test/unit/mocks/entities.js

This PR adds the `/user/me/` endpoint to be able to get the currently authenticated user.

feat(user): add `user/me` endpoint

---

lib/entities/asset.js

when doing bulk export/import I encountered a rare but possible scenario where the `this.fields.file` variable was not set. rather than letting the script fail from calling `Object.keys` on a null or undefined object, this change will simply default to an empty object. Thus, locales will be an empty array and gracefully exit the function.

fix(asset): safely handle case where file is null

---

README.md

Fixed variable name in `README > Using ES6 import` to make code example usable.

Fix code example in readme.md

---

README.md

I replaced the unpkg link with a [jsDelivr CDN link](https://www.jsdelivr.com/package/npm/contentful) in your readme. jsDelivr works similarly to unpkg but was built specifically for production usage and offers a large network and better reliability.

 chore: Replace unpkg with jsDelivr

---

package.json

With the release of Webpack 4, there's a [`resolve.mainFields` configuration](https://webpack.js.org/configuration/resolve/#resolve-mainfields), which defines which `package.json` fields are checked in which order to determine the entry point of a package import.
Without a `target`(or `target` being `web` / `webworker`) the order is the following:
```js
mainFields: ["browser", "module", "main"]
```
Angular 6 for example seems to have not altered such main fields or targets, causing https://github.com/contentful/contentful.js/issues/243.
I used the example project Khaled created here: https://github.com/contentful/contentful.js/issues/243#issuecomment-390141336
I could remove the manual `paths` mapping, and the type was correctly inferred again.

fix: add browser entry point to package.json

---

lib/create-space-api.js
package.json

Turns 
```
Deprecated: Space.getContentTypes() will be removed in version 6.0. Please migrate your code to use the new environments API.
```
into
```
Deprecated: Space.getContentTypes() will be removed in future major versions.
Please migrate your code to use Environment.getContentTypes():
https://contentful.github.io/contentful-management.js/contentful-management/latest/ContentfulEnvironmentAPI.html#.getContentTypes
```

improve deprecation message

---

lib/entities/content-type.js

Our lodash-webpack plugin removes some parts of lodash, including _.matches shorthand, which we were using in contentType omitAndDelete helper. It didn't fail for unit tests but broke integration tests.
This PR removes using lodash _.find altogether and replaces it with vanilla js find.

fix(ContentType): Use vanilla js find instead of lodash with shorthand.

---

lib/entities/locale.js
test/integration/locale-integration.js

There was a workaround for an API bug for `fallbackCode` but now it is fixed and this transformed into a bug in the SDK not being able to update a fallback locale for a given locale.
This PR fix the issue

fix(locale): fix fallBackCode update

---

lib/create-space-api.js
test/integration/integration-tests.js

This PR updates the createEnvironmentWithId method to only send the source header if the source has been provided. This behavior is desired because of future feature flagging.

feat(environments): do not send source header if sourceEnvId is not provided

---

lib/create-contentful-api.js

Fixes an issue with 404 HTTP error always returned when calling `.getPersonalAccessToken('tokenId')`

fix(access_token): Use correct HTTP method (#223)

---

lib/instance-actions.js

Now that env aliases always have a sys.version, send it and remove the safeguard (since this is what alerted me to the sys.version inconsistency in the first place).

fix(instance-actions): do not send default 0 for sys.version

---

typings/asset.d.ts

Added upload from field to the asset typings. Made details optional. (Relates to issue #235 )
This fix is needed for when you are updating an asset with a new uploaded file.

Update Asset typings

---

lib/create-environment-api.js
lib/create-space-api.js

`asset.process()` is not an available function, this PR makes it a bit clearer instead of users getting errors if they've copy pasted code example.

Docs: Update code examples for createAsset()

---

typings/contentFields.d.ts

Add missing ContentFields properties to typescript definition file `contentFields.d.ts`
Resolves #238

chore(ts): Add missing ContentFields properties

---

package.json
test/integration/integration-tests.js
typings/contentfulManagement.d.ts

Make the params `limit` and `skip` available for TypeScript users.

fix(types): Add typecheck for getSpaces query params skip and limit

---

lib/entities/asset.js
package.json

Currently when an asset has multiple locales, we trigger processing for them all individually in parallel, but when they finish we only return the result of the first triggered task.
This leads to a race condition where sometimes the version number is off, and subsequent publishing fails.
Change this logic to always return the last successfully processed asset state, which should then have the correct version for publishing.

fix: ensure to return the most recent version when processing multiple asset locales

---

typings/contentfulManagement.d.ts

The `retryLimit` option is present in the documentation and appears to work correctly in the implementation but is missing from the type declaration file, causing a type error when trying to use it in TS.

fix(typings): add retryLimit to client opts

---

CONTRIBUTING.md
lib/create-space-api.js
lib/entities/user.js
test/integration/integration-tests.js
test/integration/user-integration.js
test/unit/create-space-api-test.js
test/unit/entities/user-test.js
test/unit/mocks/entities.js

We want to add user management endpoints to the api and document them.
This pull request adds the get `/space/{spaceId}/users` endpoints.

Add  getSpaceUser and getSpaceUsers endpoint in space api

---

lib/create-organization-api.js
lib/entities/organization-membership.js
test/unit/entities/organization-membership-test.js

This is the follow up after the PR in the gatekeeper https://github.com/contentful/gatekeeper/pull/3887.
As the alpha header is not required any more, this is just a small update to the current implementation.

Removal of the alpha header

---

typings/space.d.ts

I thought the error was the code was missing the last parameter however it was just the typings that was missing that.
Should be fixed with this PR.

fix(typings): Updated typings for space.createEnvironmentWithId

---

typings/apiKey.d.ts
typings/environment.d.ts
typings/space.d.ts

These are probably not complete, just the things I found when moving the ideas from https://www.contentful.com/developers/docs/tutorials/general/continuous-integration-with-circleci/
into TypeScript.
Biggest caveat is that I expect this isn't actually where you want to export `EnvironmentAlias` from. Feel free to edit away or toss this out and do it a different way, but I wanted to make sure I at least got it submitted upstream.
I have a workaround in the meantime, that I put in my own project's `src/@types/patches/contentful/index.d.ts` - sharing in case it helps others before this or similar gets merged: https://gist.github.com/trptcolin/618214a5f22500131885b6fb89202696
refs #257

chore(types): Add missing typings for env alias and env delete

---

typings/asset.d.ts

fix(typings): Include filename, contentType assetFileProp typings

---

typings/appDefinition.d.ts
typings/contentType.d.ts

There are two errors in type definitions for `.toPlainObject` functions.
`MetaSys` scopes MetaSysProps to be in `sys` object.

fix: correct toPlainObject typings for content type and app definition

---

typings/space.d.ts
typings/user.d.ts

* Adds missing `getSpaceUsers` definition to Space type
* Adds missing `toPlainObject` definition to User type

chore: add missing type definitions for Space and User

---

lib/enhance-with-methods.js

Where there any good reasons why we disable `configurable` attribute for all additional methods? 
> Configurable. If false, any attempts to delete the property or change its attributes (Writable, Configurable, or Enumerable) will fail.
We're using https://overmindjs.org/ with contentful-management and it requires wrapping sdk object with `Proxy` object. 
`configurable: false` restricts us from doing this.

fix: allow methods to be configurable

---

package.json

Allow prerelease experimental builds from the `experimental` branch.

chore: change semantic-release configuration for experimental releases

---

lib/error-handler.ts
test/unit/error-handler-test.js

This pr restructures the `errorHandler` logic so that it always obscures the management token instead of doing so only for response errors.

Token error handling

---

lib/create-organization-api.js

Small docs fix to resolve this github issue: https://github.com/contentful/contentful-management.js/issues/332
working example:
const contentful = require('contentful-management')
const client = contentful.createClient({ accessToken: '<content_management_api_key>' })
client
.getOrganization(orgId)
.then((organization) => organization.getTeams())
.then((teams) => console.log(teams))
.catch(console.error)

fix(organizationApi): correct getTeam() and getTeams() documentation

---

.circleci/config.yml
package.json

Prevent docs being updated with non-master (latest) NPM releases

chore: publish docs only from master branch releases

---

.circleci/config.yml
package.json

Rolls back to previous publishing workflow but with additional branch check (only for master branch)

chore: documentation release

---

lib/create-environment-api.ts
lib/entities/asset.ts
lib/entities/space.ts
lib/plain/endpoints/asset.ts
lib/plain/endpoints/entry.ts
lib/plain/endpoints/environment.ts
lib/plain/endpoints/index.ts
lib/plain/endpoints/space.ts
lib/plain/plain-client.ts

Adds the `asset` endpoint (similar to `entry`) to the plain CMA client. Adds a way to specify headers for `update` calls.

feat: add asset endpoint and update headers to plain cma client

---

lib/common-types.ts
lib/entities/entry.ts

Adds missing deleted and archived props to `MetaSysProps`. Make `Entry` use `MetaSysProps` instead of `BasicMetaSysProps`.

fix: add missing MetaSysProps types for archived and deleted states

---

lib/common-types.ts
lib/create-environment-api.ts
lib/create-space-api.ts
lib/entities/environment.ts
lib/plain/endpoints/common-types.ts
lib/plain/endpoints/environment.ts
lib/plain/plain-client.ts

Exposes all environment-related endpoints to a plain CMA client and reuses endpoints in the original CMA client internals.

feat: move all environment methods to plain client

---

lib/create-environment-api.ts
lib/entities/locale.ts
lib/plain/endpoints/locale.ts
lib/plain/plain-client.ts
test/unit/mocks/entities.js

Extracts all available locale endpoints to the plain client and refactors the main client to use these endpoint methods.

 feat: extract all locale methods

---

lib/common-types.ts
lib/contentful-management.ts
lib/create-environment-api.ts
lib/entities/content-type.ts
lib/plain/checks.ts
lib/plain/endpoints/content-type.ts
lib/plain/endpoints/editor-interface.ts
lib/plain/endpoints/entry.ts
lib/plain/plain-client.ts
test/unit/create-environment-api-test.js
test/unit/mocks/entities.js

Add all existing endpoints for content types to plain client and makes current client used these endpoints.

feat: move content type methods

---

.circleci/config.yml

Will reduce build time in PRs/branches.

build: only run release step when we actually release

---

lib/common-types.ts
lib/entities/asset.ts
lib/entities/entry.ts

Asset returned from CMA doesn't have `sys.locale`, so I removed it. This makes Entry and Asset `sys` compatible, so `EntityMetaSysProps` is extracted as a common type and use for both of them.

fix: unify asset and entry types, remove non-existing 'locale' from asset.sys

---

.gitignore
README.md
lib/common-types.ts
lib/common-utils.ts
lib/create-environment-api.ts
lib/entities/asset.ts
lib/entities/entry.ts
lib/entities/index.ts
lib/entities/tag.ts
test/integration/environment-integration.js
test/integration/integration-tests.js
test/integration/tag-integration.js
test/unit/create-environment-api-test.js
test/unit/entities/asset-test.js
test/unit/entities/entry-test.js
test/unit/entities/tag-test.js
test/unit/mocks/entities.js
test/unit/test-creators/static-entity-methods.js

Add tag management to the SDK. Content tags are only available on the CMA, and used to organize content within the web app. Tags live under the `metadata` property, a new top-level property on entries and assets. 
This PR includes:
* CRUD operations on tags (via Environment API)
* updates to `entry` and `asset` typings to include the optional metadata property
* tests for entry and asset to confirm `metadata` is included in the payload and can be updated from those entities
Example:
```js
const env = await space.getEnvironment('main')
const entry = await env.getEntry('myEntry')
// create a tag
const myTag = await env.createTag('myTagId', 'myTagName')
// update entry with tag
entry.metadata.tags.push(myTag)
await entry.update()
// update tag name
myTag.name = 'my new tag name'
await …
```

feat(tags): management

---

lib/common-types.ts
lib/create-environment-api.ts
test/integration/tag-integration.js

We should send a query params object in getTags (for consistency with our other get-collection endpoints in the SDK).

feat(getTags): send query params object

---

lib/entities/asset.ts

Creating assets is possible without providing a description.
E.g. the asset call here also doesn't have one https://www.contentful.com/developers/docs/references/content-management-api/#/reference/assets/asset

fix: optional asset description

---

lib/entities/space-member.ts
lib/entities/space-membership.ts
lib/entities/team-space-membership.ts

Fixing the typings for the roles in createTeamSpaceMemberships to address this https://github.com/contentful/contentful-management.js/issues/388.

fix: typings for roles in space memberships

---

lib/entities/editor-interface.ts

Closes https://github.com/contentful/contentful-management.js/issues/401 and https://github.com/contentful/contentful-management.js/issues/399

fix: add missing settings to editorInteface type definition

---

lib/create-space-api.ts
lib/plain/endpoints/scheduled-action.ts
lib/plain/plain-client.ts

Changes in the PR:
- Fixing typo `scheduledActons`  -> `scheduledActions`
- Rename method `query` -> `getMany` for better consistancy

fix: typo in scheduled actions, rename query -> getMany

---

test/integration/integration-tests.js
test/integration/tag-integration.js

We accidentally only ran tests for tags. 
This PR removes the only, and ensures unique names for all tags created during tests to avoid name collision.

fix(tests): content-tags

---

lib/create-space-api.ts
lib/entities/environment-alias.ts
test/integration/environment-alias-integration.js
test/integration/integration-tests.js

Adds methods for managing custom environment aliases.
This method is currently only available to a limited amount of customers.
Restrictions and constraints are only enforced on the API side and no additional logic is added to the SDK.

feat: custom environment aliases

---

lib/entities/app-installation.ts

fixes issue https://github.com/contentful/contentful-management.js/issues/440. We can not use the `createDeleteEntity` helper since an `AppInstallation` does not have its own id and uses the id of an `AppDefinition`.

fix(AppInstallation): use app definition id for deleting an app installation

---

test/integration/integration-tests.js

On cleanup explicitly target environment instead of alias.
To unblock https://github.com/contentful/contentful-management.js/pull/530

fix(test): on cleanup explicitly target environment instead of alias

---

lib/create-space-api.ts
test/integration/role-integration.js

There is currently no support in the sdk that allows to provide query params to `getRoles`. This pr adds it.

Add support for query params for getRoles method

---

lib/entities/environment.ts
lib/entities/organization.ts
lib/entities/space.ts
test/unit/entities/environment-test.js
test/unit/entities/organization-test.js

We don't need to reinitialize http clients anymore since all endpoints use full endpoint paths instead of relative paths.

refactor: remove all url wrappers

---

lib/plain/endpoints/raw.ts
lib/plain/plain-client.ts

`contentful-migration` exposes a way to access to all HTTP verbs easily to make the shift easier this is reflected in the plain endpoint.

feat: additional raw endpoint for easy access to all HTTP verbs

---

mocharc.js
package.json
test/cleanup-spaces.js
test/integration/environment-integration.js
test/mocha-global.js
test/mocha.opts

Teardown all created test spaces that exists > 1h after each run.
This should help to kill zombis spaces left alive after a run got intercepted.

chore: ensure teardown of all test spaces

---

lib/create-environment-api.ts
lib/entities/environment.ts
lib/entities/upload.ts
lib/error-handler.ts
lib/plain/endpoints/asset.ts
lib/plain/endpoints/upload.ts
lib/plain/plain-client.ts
lib/upload-http-client.ts
test/unit/create-environment-api-test.js
test/unit/mocks/http.js

Fixes https://github.com/contentful/contentful-management.js/issues/584
Apparently, we did a mistake while migrating to a new plain API and scoped uploads to environments while upload are bound only to a space. Integration tests don't cover this part so it was never caught.

fix: correct file uploads

---

test/integration/content-type-integration.js

Use existing content type for test, instead of creating a new one on every run and eventually hitting the space limit.

chore: fix contenttype integration test.

---

lib/create-cma-http-client.ts
package-lock.json
package.json

Bumps `contentful-sdk-core` to leverage the ability to get access token asynchronously and pass `onError` & `onBeforeRequest` interceptors.
See: https://github.com/contentful/contentful-sdk-core/releases/tag/v6.7.0 

feat: allow getting accessToken async

---

lib/create-cma-http-client.ts

To be able to override user agent when necessary (for example in the main Contentful web application)

fix: allow required headers to be overwritten by custom ones

---

lib/error-handler.ts

Account for a case when `config` is undefined.

fix: check for undefined config in error handler

---

lib/plain/endpoints/raw.ts
lib/plain/plain-client.ts

Makes it easier to type raw methods in plain client version.

fix: improve generics in raw plain client endpoints

---

lib/create-contentful-api.ts
lib/entities/user.ts
lib/plain/endpoints/user.ts
test/unit/create-contentful-api-test.js

Allow for query parameters to be passed to `/users/me` path to fetch additional fields
Currently the `getCurrentUser()` method does not accept additional params, meaning certain fields aren't returned by the API. This allows for query params to be passed, plus overriding the returned type

feat(getCurrentUser): allow for query params to be passed

---

lib/plain/plain-client.ts

I have noticed that optional params that were added to uset.getCurrent() weren't exposed and typed.
In this PR we fix that
I was  not able to use wrap() wrapper because that would add unnecessary default params, which aren't supported by the getCurrent() function.
I was not able to use werapHttp() because it didn't support any params, and adjusting it wasn't possible due to genric types, so I ended up with a custom wrapping types

feat: optional params for user.getCurrent()

---

lib/create-cma-http-client.ts
lib/create-environment-api.ts
package-lock.json
package.json

Be able to directly delete an entry by its Id
Avoid using the plain client for that purpose. 
I need to delete an entry which I already now its sys.id
With this new method, I can delete the entry without calling  getEntry(id)  and then entry.delete() which produce 2 API calls

feat: be able to directly delete an entry by its Id

---

lib/adapters/REST/endpoints/raw.ts
lib/adapters/REST/rest-adapter.ts
lib/contentful-management.ts
lib/create-adapter.ts
lib/create-contentful-api.ts
test/unit/contentful-management-test.js
test/unit/create-adapter-test.js
test/unit/create-contentful-api-test.js

Add tests for `createClient` & `createAdapter`.
Also, this PR fixes an issue when using `client.rawRequest`.

test: add tests for new adapter architecture

---

lib/plain/wrappers/wrap.ts

TypeScript generates very complicated typings for `wrap.ts`: https://unpkg.com/contentful-management@7.13.0/dist/typings/plain/wrappers/wrap.d.ts. These typings cause errors when using `contentful-management` in a TypeScript project as TypeScript cannot parse them (see #775).
I don't know what's the underlying issue of the problem.
This PR fixes the type errors by simplifying the type definition of `WrapFn`. The previous types were unnecessarily complex by using `MROpts`. The new types use `MRActions` directly which results in the same level of type safety but with a less complex output.

fix: type issues in wrap.d.ts

---

lib/adapters/REST/endpoints/app-bundle.ts
lib/adapters/REST/endpoints/index.ts
lib/common-types.ts
lib/create-app-definition-api.ts
lib/entities/app-bundle.ts
lib/entities/app-definition.ts
lib/entities/index.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/unit/create-app-definition-api-test.js
test/unit/entities/app-bundle-test.js
test/unit/mocks/entities.js
tsconfig.json

Introducing the `AppBundle` entity with the following methods:
- create
- get
- getMany
- delete
Added the entity to the flat and nested client and exported all relevant types. Also adjusted the `AppDefinition` API to support the `AppBundle` entity for the nested client.

feat(AppBundle): support AppBundle entity [EXT-2641]

---

lib/adapters/REST/endpoints/app-definition.ts
lib/adapters/REST/endpoints/app-upload.ts
lib/adapters/REST/endpoints/index.ts
lib/common-types.ts
lib/create-organization-api.ts
lib/entities/app-upload.ts
lib/entities/index.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
package.json
test/unit/create-organization-api-test.js
test/unit/entities/app-upload-test.js
test/unit/mocks/entities.js
tsconfig.json

Introducing the `AppBundle` entity with the following methods:
- create
- get
- delete
Added the entity to the flat and nested client and exported all relevant types. Also adjusted the `Organziation` API to support the `AppUpload` entity for the nested client.

feat(AppUpload): support AppUpload entity [EXT-2641]

---

lib/adapters/REST/endpoints/app-bundle.ts
lib/adapters/REST/endpoints/app-definition.ts
lib/adapters/REST/endpoints/app-upload.ts
lib/adapters/REST/endpoints/index.ts
lib/common-types.ts
lib/create-app-definition-api.ts
lib/create-organization-api.ts
lib/entities/app-bundle.ts
lib/entities/app-definition.ts
lib/entities/app-upload.ts
lib/entities/index.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/unit/create-app-definition-api-test.js
test/unit/create-organization-api-test.js
test/unit/entities/app-bundle-test.js
test/unit/entities/app-upload-test.js
test/unit/mocks/entities.js
tsconfig.json

This PR introduces the AppBundle and AppHosting entities to the SDK

feat(AppHosting):  support AppBundle and AppUpload entities [EXT-2641]

---

lib/adapters/REST/endpoints/http.ts
test/unit/adapters/REST/endpoints/http-test.js
test/unit/mocks/http.js

v7.13 introduced a bug where the payload and the axios configuration for `raw.post` and `raw.put` was not set correctly.
The error was a wrong argument order.
This PR fixes the invalid order and adds unit tests to prevent this from happening again.

fix: correctly set payload & headers when using raw.post & raw.put

---

lib/adapters/REST/endpoints/entry.ts
lib/adapters/REST/endpoints/raw.ts
lib/adapters/REST/rest-adapter.ts
lib/common-types.ts
lib/entities/entry.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
package-lock.json
package.json
test/integration/entry-integration.js
test/unit/entities/entry-test.js
test/unit/test-creators/instance-entity-methods.js

Adds support for [patching an entry](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entry/patch-an-entry/console/curl).

feat: [PEN-1508] add entry patch support

---

lib/adapters/REST/endpoints/asset.ts
lib/adapters/REST/endpoints/entry.ts
lib/plain/common-types.ts

Add an optional `headers` parameter to `entry.get` and `asset.get` in the plain client
In order for our shared `EntityRepo` to work with the plain client it needs the ability to set those headers

feat: add optional headers param to entry/asset GET

---

lib/adapters/REST/endpoints/tag.ts
lib/entities/tag.ts
lib/plain/common-types.ts

While interacting with the plain client, I figured out that the provided types are wrong (my bad in the first place as I did the types for `Tag`).
This PR introduces dedicated types for tag `create`, ùpdate` and `delete`.

fix(plain-client): tag param types

---

test/integration/entry-integration.js

We added a new content model to test entry with multiple [references](https://github.com/contentful/contentful-management.js/pull/829), this causes tests to fail in other PRs

fix: add new content model to tests

---

.circleci/config.yml

There is a `presemantic-release` script taking care of building.

ci: dont build twice for release

---

lib/adapters/REST/endpoints/upload.ts
package-lock.json
package.json

The client creation parameters don't handle axios's `maxBodyLength` so it's always -1. This makes big file uploads failing.
As a temporary solution while the `maxBodyLength` is handled in `contentful-sdk-core` we can set the value equal to `maxContentLength` which already is
Costumer reports failing upload with big files
Once [this pr](https://github.com/contentful/contentful-sdk-core/pull/152) for `contentful-sdk-core` is merged we will be able to use a separate `maxBodyLength`

fix: failing big files upload

---

lib/adapters/REST/endpoints/entry.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/entry.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/defaults.ts
test/integration/entry-references-integration.ts
test/unit/entities/entry-test.js
test/unit/mocks/entities.js
test/unit/test-creators/instance-entity-methods.js

Add `references` to entry api
Add `getReferences` to environment api

feat: add entry references to entry and environment methods []

---

lib/create-environment-api.ts
lib/entities/entry.ts
test/integration/entry-references-integration.ts

Refactor `getEntryReferences` and `entry.references` to use named args instead of positional

refactor(entry-references): use named args instead of positional

---

lib/create-environment-api.ts

Last commit wasn't release due to `refactor` keyword in commit message
https://app.circleci.com/pipelines/github/contentful/contentful-management.js/2686/workflows/93f05bb5-55af-4fac-a4f5-8e22079493aa/jobs/7616

fix: entry references conventional commit release

---

lib/entities/scheduled-action.ts
test/unit/mocks/entities.js

Add" timezone" to schedule action props i.e : 
scheduledFor: {
datetime: datetime,
timezone: timezone,
}

chore: add timezone to schedule action props

---

lib/create-environment-api.ts
lib/entities/release.ts
test/unit/entities/release-test.ts

- This PR fixes the JSDoc example for Releases (incorrect shape for Link object)
- Fixes the typing for query methods

fix(release): jsDoc examples and typing

---

lib/adapters/REST/endpoints/scheduled-action.ts
lib/common-types.ts
lib/entities/scheduled-action.ts
lib/plain/common-types.ts

Deleting a scheduled action is impossible as it throws an error "Missing environment id". This PR fixes it

fix: require env id as an argument to scheduled actions delete function

---

package-lock.json
package.json

- Fixes #848 
- Update `type-fest` to 1.1.3 - the previous version didn't include the `simplify.d.ts` file.
- [N/A] Changes are reflected in the documentation
- [N/A] The new method is exported through the default and plain CMA client
- [N/A] All new public types are exported from `./lib/export-types.ts`
- [N/A] Added a unit test for the new method
- [N/A] Added an integration test for the new method
- [N/A] The new method is added to the documentation

fix(type-fest): update type-fest to include simplify.d.ts

---

.github/dependabot.yml
package-lock.json
package.json

We version conflicts with `type-fest` when used in other projects. With this changes, we downgrade the version of `type-fest` to unblock users. 
We will investigate further how and when we can update again.

fix(deps): downgrade type-fest

---

lib/entities/task.ts

Add a new dueDate field to the Task property.

feat: add due date as a task field type [HOMER-78]

---

lib/entities/content-type-fields.ts

[DANTE-46]
Amends declaration of the content type field type to support the `initialValue` property
The property declaration follows the `fields` property in `EntryProps` type, i.e. `<T = KeyValueMap>`
[DANTE-46]: https://contentful.atlassian.net/browse/DANTE-46

feat: initialValue property in content type field

---

lib/entities/scheduled-action.ts

Add `version`, `updatedAt` and `updatedBy` to `ScheduledSysProps`

chore: update scheduled action sys props []

---

lib/create-contentful-api.ts
lib/create-space-api.ts
test/integration/space-team-integration.js
test/unit/create-space-api-test.js

It's `SpaceApi.getTeams`, not `SpaceApi.getSpaceTeams`.
[Related open App-SDK PR](https://github.com/contentful/ui-extensions-sdk/pull/797/files)
[Previous PR](https://github.com/contentful/contentful-management.js/pull/873)

fix: use correct name for new method [HOMER-75]

---

lib/entities/task.ts

Assign tasks to teams via CMA.
Enhance the `assignedTo` type to also include links to teams. Since everything is passed through, there are no other code changes required.
This is part of Team Homer's first project.

feat: enable teams to be assigned to tasks [HOMER-69]

---

lib/contentful-management.ts

This PR exports RestAdapter so it can be initialized outside of cma.js and passed into `createClient`

feat: export RestAdapter

---

lib/entities/release.ts

Adds `lastAction: Link<'ReleaseAction'>` to `sys` typing of `Release` entity

chore: add lastAction to release sys types

---

.eslintrc.js
package-lock.json
package.json
test/integration/space-team-integration.js

- Tests weren't correctly running as there was a `.only` usage in the tests.
- Adds a linter check to prevent `.only` 
- [N/A] Changes are reflected in the documentation
- [N/A] The new method is exported through the default and plain CMA client
- [N/A] All new public types are exported from `./lib/export-types.ts`
- [N/A] Added a unit test for the new method
- [N/A] Added an integration test for the new method
- [N/A] The new method is added to the documentation

fix(tests): remove .only from spec file

---

lib/adapters/REST/endpoints/scheduled-action.ts
lib/common-types.ts
lib/create-space-api.ts
lib/entities/scheduled-action.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/defaults.ts
test/integration/scheduled-action-integration.ts
test/unit/create-space-api-test.js
test/unit/entities/scheduled-action-test.js
test/unit/mocks/entities.js

Adds support for 
```js
plainClient.scheduledActions.update();
spaceClient.updateScheduledAction();
scheduledAction.update();
```

Feat: update scheduled actions [SPA-284]

---

lib/plain/common-types.ts
lib/plain/plain-client.ts

It adds the `create` and `createWithId` call in the plain client for `contentType`. 
Was not implemented yet.

feat: add create and createWithId to contentType in plain client

---

lib/adapters/REST/endpoints/scheduled-action.ts
lib/common-types.ts
lib/create-space-api.ts
lib/entities/scheduled-action.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/scheduled-action-integration.ts
test/unit/entities/scheduled-action-test.js

- Adds `getScheduledAction`, previously missing from the SDK support.
- Adds the `read` method for a scheduled Action and refactor some tests to use it.
- It was missing from the overall SDK support

feat(scheduledActions): add get and delete function [SPA-321]

---

README.md

We are not using travis anymore but still displayed its badge.

docs: replace travis with circleci badge

---

lib/entities/scheduled-action.ts
lib/plain/common-types.ts

Added error in ScheduledActionsProp
We have a [CEP](https://contentful.atlassian.net/wiki/spaces/ENG/pages/3282698277/CEP-0117+Add+error+to+scheduled+actions+payload) written with all the details and security considerations. 
- Tracking error types for BI data warehousing (e.g. Segment)
- Exposing historical scheduled action errors in Contentful Launch
- Exposing historical scheduled action errors via customer API
- Sending errors via webhooks to external systems

feat(scheduledAction): Expose error on Scheduled Actions API [SPA-314]

---

lib/entities/content-type-fields.ts

Rename `initialValue` property `defaultValue` in  content type field type.
Rename `initialValue` property `defaultValue` in  content type field type.
See [DANTE-182](https://contentful.atlassian.net/browse/DANTE-182) and [DANTE-189](https://contentful.atlassian.net/browse/DANTE-189). After concluding the _inital values_ EAP it was decided to rename the feature _default values_. Because the feature was only available in the EAP, we don’t consider this a breaking change.

fix: rename initialValue property defaultValue [DANTE-182]

---

lib/entities/editor-interface.ts
lib/export-types.ts
test/integration/task-integration.js

Add types for `groupControls` and `editorLayout` properties of the `EditorInterface`.

feat: field groups props in editor layout [DANTE-173]

---

lib/entities/extension.ts

Closing https://github.com/contentful/contentful-management.js/issues/868
`createUiExtension` and `createUiExtensionWithId` always expects the second argument to be wrapped in extension, only the types for this weren't correct.
This adjusts the types to be what we expect in the function

fix: adjust create ui extension types

---

lib/entities/release.ts

This PR adds the newly-support `title[match]` operator on Release.query operations.

feat(releases): expose title[match] on release query

---

README.md
package-lock.json
package.json

Introduce an [optional parameter](https://github.com/contentful/contentful-sdk-core/blob/master/src/types.ts#L108) to limit the number of requests sent per second to not exceed [rate limits](https://www.contentful.com/developers/docs/technical-limits/).
With that, we're not only relying on retries based on `429` responses but can also control the max count of requests we send per second.
See [description](https://github.com/contentful/contentful-management.js/compare/feat/request-throtteling?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R339-R344) of parameter

feat(requests): introduce throttleing

---

.github/dependabot.yml
package-lock.json
package.json

pin webpack version to < 5 until we switch to a webpack-free build solution

fix(chore): webpack version

---

lib/plain/as-iterator.ts

Some endpoint like editor_interfaces do not return skip and limit params, that needs to be mitigated to properly consume items.

fix: add sane defaults to mitigate rogue endpoints

---

lib/constants/editor-interface-defaults/sidebar-defaults.ts

Remove the legacy deprecated tasks for configuration constants.

chore: remove deprecated tasks from sidebar config

---

lib/common-utils.ts
lib/entities/release.ts
lib/plain/common-types.ts
test/integration/release-integration.ts

Changes the return type of releases `getReleases` and `plainClient.release.query` calls to return `CursorPaginatedCollectionProp` instead of `CollectionProp` (wrapped in `Promise` of course)

fix: mark get many releases to return cursor based collection [SPA-505]

---

lib/contentful-management.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/scheduled-action-integration.ts

The alpha feature introduced in https://github.com/contentful/contentful-management.js/pull/1114 should be protected by a `alphaFeatures` parameter which needs to contain a certain string to add the workflows endpoint to the plain client. Now, typescript understands whether the array really includes this string. If not, the type of the returned client doesn't contain `workflowDefinition`.
I started with this [magic solution to a similar problem](https://stackoverflow.com/a/57958451/4816930). I did some testing [on this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggTnAhiAsgSwHYHkPQLxQDaAzsHJgOYA0UAdPaeRhYQLqsBQHAxgPYakoADwBcsBMnTZcUAoQBEwCKXmcOoSOKQgAYrzjcIAEwCSSgLYAeDlCgAlKBCFKMR4lEaUqNqABVHzhCu7gAUdhCIRvwANiDw2paezAB8UAA+UHARURixRHasAJRQAGQ+tgDeRADSUJhQANYQILwAZn6sYlWE …

feat: improve PlainClientAPI type to listen to an explicit string

---

lib/entities/workflow-definition.ts

TLDR; I accidentally type validationLinks as an array with exactly one item. This would break right away because we probably will start with no validation links being defined.

fix: dont enforce an array with exact one item for workflow validation links

---

lib/entities/workflow-definition.ts

Update the typings from workflow definition and steps to match the original API proposal.
- Permission is part of the step entity
- "applicableEntities" should be "appliesTo"

fix: move permissions property fron wf def to wf step

---

lib/entities/webhook.ts
test/integration/webhook-integration.js

Add active property to webhooks. It will always be defined in the API response, but is optional when creating and updating webhooks. It not present, it defaults to true.

feat: [EXT-3396] add active property to webhooks

---

lib/adapters/REST/endpoints/organization.ts
lib/common-types.ts
lib/create-contentful-api.ts
lib/plain/common-types.ts
test/helpers.js
test/integration/organization-integration.ts

Adds ability to pass pagination query parameters to
`plainClient.organization.getAll()` and `client.getOrganizations()`
Before it would only fetch up to 25 organizations. With the changes in this PR, there will be ability to fetch more organizations.
Users who had more than 25 organizations were not able to see more than 25 in response

feat: organizations query param support [SPA-50]

---

lib/adapters/REST/endpoints/workflow.ts

In a previous PR, we invented the workflows methods to the CMA but used the singular form which ended up in calling a not existing endpoint in the frontend.

fix(workflows): use correct API endpoint for workflows

---

lib/entities/workflow.ts

Another issue in the workflows endpoint adapter

fix(workflows): use correct param key for query []

---

lib/adapters/REST/endpoints/workflows-changelog.ts
lib/common-types.ts
lib/plain/common-types.ts

Accidentally, we used `/workflows-changelog` instead of `/workflows_changelog`.

fix(WorkflowsChangelog): use correct endpoint URL and enforce passing query for now

---

lib/entities/workflows-changelog-entry.ts

Fix the entity link type to from entity to entry

fix: the entity link type to from entity to entry []

---

README.md

Change the ES6 import part of the README to a working suggestion
Both previous variants of the ES6 import suggestion in the README did not work. While the new variant works it is important to note that it does not actually serve the ESM build present in `dist/es-modules` but the `/dist/contentful-management.node.js` bundle.
In my tests I was able to force the package to serve the ESM variant by adding the following change in the package.json
`"exports":{
"import":"./dist/es-modules/contentful-management.js"
}`
That alone leads to the error:
`import { getUserAgentHeader } from 'contentful-sdk-core';
^^^^^^
SyntaxError: Cannot use import statement outside a module`
I assume because the closest package.json still suggests that this is using CommonJS. Forcing it by changing the file name to …

fix(readme): Change ES6 import suggestion

---

lib/adapters/REST/endpoints/http.ts
test/unit/adapters/REST/endpoints/http-test.js
test/unit/mocks/http.js

At the moment using `cma.raw.patch` fails with `Unknown endpoint` thrown in https://github.com/contentful/contentful-management.js/blob/master/lib/adapters/REST/rest-adapter.ts#L69-L71 It looks to me like the `patch` method is just missing in the Http endpoint module.
Add a patch method to the Http endpoint module.

fix: Allow raw patch requests

---

lib/adapters/REST/endpoints/comment.ts
lib/adapters/REST/endpoints/task.ts
lib/common-types.ts
lib/create-entry-api.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts

- Add task.getManyForEntry
- feat: rename to getManyForEntry for consistency and allow passing pagination parameters
BREAKING CHANGE: Rename `getAll` to `getManyForEntry` for tasks and comments in plain client.
Due to pipeline issues in https://github.com/contentful/contentful-management.js/pull/1262 and some missing fixes & improvements I cherry picked the commit by @dmsolutionsmn (for keeping authorship) and added the refactoring & fix.

feat: rename getAll to getMany for tasks and comments

---

lib/entities/release.ts
test/integration/release-integration.ts

- Adds more type hints for the possible query options when using `environment.getReleases` (Client) or `releases.getMany` (PlainClient)
- More type hints and explanations for the filters available when querying releases.

feat(release): update release query options type with new query params [SPA-538]

---

test/integration/release-integration.ts

- A `.only` flag ended up being committed into `master`, this PR removes the flag.

fix(tests): remove .only from release test []

---

lib/adapters/REST/endpoints/release-action.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/release-action.ts
lib/entities/release.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/environment-integration.js
test/integration/release-action-integration.ts
test/integration/task-integration.js

Adds support for the new `GET /release_actions` endpoint, that is replacing the existing `GET /releases/:id/actions`
This new endpoint supports querying for multiple releases, actions or specific properties.
- Change the usage of `/releases/:id/actions` to use the new `/release_actions` endpoint
- Add deprecation notice for passing `releaseId` instead of `query { 'sys.release.sys.id[in]`: ... } `
- Add specs covering new query params

feat: add support for release actions query endpoint [SPA-707]

---

package.json

Add `browser` field to `package.json`.
Any reason why this wasn't done before?
When using contentful-management in browser context without esm support, the node bundle is used. This bundle requires native node libraries that are not available in the browser. For that reason you cannot use CMA.js in stackblitz: https://stackblitz.com/edit/js-u7mabv
By adding the `browser` field, the correct bundle (should) be selected and stackblitz should work correctly.
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#browser

fix: add browser field to package.json

---

lib/entities/app-action.ts
lib/export-types.ts
package-lock.json

forgot to expose the new type in #1328  🤦🏾 

fix(ApiAppActionCategories):  export the actual type [EXT-3618]

---

lib/entities/workflow-definition.ts
test/unit/mocks/entities.js

- To indicate that a workflow is locked and adjust the layout, we need to add the `isLocked` field to the SDK.
- Updated tests

feat: added isLocked to WorkflowDefinitionSysProps

---

lib/adapters/REST/endpoints/app-action.ts
lib/common-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/app-action-integration.ts

Adds the method for listing all app actions of an environment. 
url: `/spaces/:sid/environments/:env_id/actions`

feat: [] add app action list for env

---

lib/adapters/REST/endpoints/task.ts
lib/create-entry-api.ts

Add query parameters to the entry tasks endpoint.

feat: add entry tasks params support [ZEND-2486]

---

lib/adapters/REST/endpoints/entry.ts
lib/plain/common-types.ts

Similar to [this PR](https://github.com/contentful/contentful-management.js/pull/808), we need to pass headers now when fetching entries in one specific use case. The launch app needs to pass it, to get the automation tags for all entries related to workflows.

feat: allow passing headers when fetching multiple entries [HOMER-1033]

---

lib/entities/app-definition.ts

We need to allow 'home' to be passed as a location when creating a new app definition. This will allow users to create app definitions that can be rendered in the new 'home' location, that we will be supporting from now on.
Update the app definition location type to include 'home'

feat: [EXT-3864] add home to app locations

---

lib/create-contentful-api.ts

`createSpace` params types are missing `defaultLocale` and misleading in TS environment
As per [docs](https://www.contentful.com/developers/docs/references/content-management-api/\#/reference/spaces/spaces-collection/create-a-space/console/js) our CMA API supports it
See https://github.com/contentful/contentful-cli/pull/1583#discussion_r957541315

fix: add defaultLocale to SpaceProps

---

lib/adapters/REST/endpoints/app-definition.ts
lib/adapters/REST/endpoints/app-installation.ts
lib/common-types.ts
lib/create-app-definition-api.ts
lib/entities/app-definition.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts

Following the correct format and trying to move the endpoint for clarity.
Shift the getInstallationsForOrg function and change the action and entity if possible for the endpoint.
The endpoint should follow this pattern: cma.appInstallation.getForOrg()
Merge app is using this endpoint. Remove the old endpoint after changes in Merge app.
https://github.com/contentful/merge-app/blob/main/src/core/hooks/data/useFetchEnvironments.ts#L12

fix: move getForOrganization to AppInstallation entity [EXT-3877]

---

test/helpers.js
test/integration/release-action-integration.ts
test/integration/release-integration.ts
test/mocha-global.js

Improves the deletion of test spaces created during integration tests. 
Things done: 
- set lower threshold for space cleanup (10 minutes instead of 1 hour)
- add missing space cleanup to tests that create test spaces
- add a global `before`, as the `after` doesn't always run (e.g. when you stop the test run midway)

chore: improve test space deletion 

---

lib/entities/entry.ts
lib/export-types.ts

This PR is for adding urn as an optional parameter to EntityMetaSysProps.
The type is used in field-editors repository. For this [PR](https://github.com/contentful/field-editors/compare/DANTE-648-urn-from-api-for-entries?expand=1) to get merged we need this change.

feat: add urn to entity meta sys props

---

lib/entities/content-type-fields.ts
lib/entities/field-type.ts
test/integration/content-type-integration.js
test/integration/entry-integration.js

This PR was created to support the new Cross Space fields added in the creation of content types and entries.
the new xspace field type should be recognized and handled in the JS SDKs
also when editing content types and entries with xspace fields
we do not implement xspace links resolution in the SDK, just return the link object/CRN as is

feat: support xspace fields [Dante-708]

---

lib/adapters/REST/endpoints/organization-membership.ts
lib/common-types.ts
lib/create-organization-api.ts
lib/plain/common-types.ts
test/integration/organization-membership-integration.js

Apply provided params to the http client, to fetch `organizationMemberships` paginated

fix(organizationMemberships): query many paginated [ZEND-2681]

---

lib/common-types.ts
lib/entities/scheduled-action.ts
test/integration/scheduled-action-integration.ts

Update scheduled actions types as per https://contentful.atlassian.net/wiki/spaces/ENG/pages/3891691521/CEP-0144+Enable+jobs-api+to+process+entry+aggregates#Recommended-Solution

feat: update scheduled actions types [SPA-900]

---

lib/contentful-management.ts

resolve #1493
Previously we had a generic that allows passing any array as long as it contains the string `workflows` so we ship the alpha client with this feature activated. This "black magic" from the SO post I linked in the comment doesn't work anymore for TS v4.8.x so I decided to keep it as simple as possible until we actually need a more general solution. Right now, workflows is the only alpha feature so it's fine to reduce this to a minimum.
Pointed out by users: https://github.com/contentful/contentful-management.js/issues/1493
PR that introduced this generic type: https://github.com/contentful/contentful-management.js/pull/1122

fix: reduce the generic typings to be compatible with TS v4.8

---

lib/adapters/REST/endpoints/app-definition.ts
lib/adapters/REST/endpoints/app-installation.ts
lib/adapters/REST/endpoints/utils.ts
lib/create-app-definition-api.ts
test/unit/adapters/REST/endpoints/utils-test.js

This PR contains 2 bug fixes: 
1/ Fix for a bug in `normalizeSpaceId` - we didn't remove the `spaceId` property from the query, now we do
2/ Handle the org id query param like other query params instead of doing string concatenation.

fix: fix query params for org installation calls

---

README.md

Fixing the client init example with environment alias (should be same as [in the docs](https://www.contentful.com/developers/docs/extensibility/app-framework/sdk/#using-the-contentful-management-library)).

docs: [] createClient example

---

lib/common-types.ts
lib/entities/scheduled-action.ts

Follow up PR of #1511 to align cursor based pagination with the spec.
This aligns the typing of the `pages` property in the response object of a collection to the spec.

fix: pages typing for cursor based pagination [MONET-883]

---

lib/adapters/REST/endpoints/asset.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/asset.ts
lib/upload-http-client.ts
test/helpers.js
test/integration/asset-integration.js

We saw that occassionally asset uploads would fail for bigger files (on slower connections) since the default upload timeout would be 30 seconds. This PR changes the default timeout to 5 minutes and provides the option to set the upload timeout as an option in the `createAssetFromFiles` function.
Setting the timeout to 100 seconds could then look something like this:
`environment.createAssetFromFiles(fileData, { uploadTimeout: 100000 })`
I realize that there are many variants how to get those options into the library. I found this to be the most straightforward one without applying this option to functions you might not expect to be affected. I am very happy about any suggestions though.

fix(assets): fix asset upload timeout []

---

lib/entities/entry.ts

When entry references are not resolvable, the return payload contains an `errors` property with some information. 
This was not reflected in the types yet.

fix: add optional 'errors' property to entry reference return type

---

lib/adapters/REST/endpoints/app-action-call.ts
lib/common-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts

Introduce a new function to receive `AppActionCall` details.

feat(app-action-call): add get details function [NONE]

---

lib/constants/editor-interface-defaults/controls-defaults.ts

Default widget fallbacks are breaking when a widgetId is not explicitly passed to the Field component in default field editors.
Adding support here for the `getDefaultControlOfField` to return resource editor widget ids instead of invalid field type.

chore: adding default widget fallback support for xspace [ZEND-3052]

---

.circleci/config.yml

We should at least build with node `16.x`, and we should only use `npm ci`

chore/bump node version on CircleCI [NONE]

---

.circleci/config.yml
package.json

- Introduce proper dependency caching ([following best practices with soft caching](https://contentful.atlassian.net/wiki/spaces/PROD/pages/4106944577/Research+Outcomes+Topics+Assemblies))
- We also removed the default behavior of building the project after every checkout, as it's only required for the release, and we have a `presemantic-release` npm command in place.

chore: improve CIrcleCI config by better caching [NONE]

---

lib/entities/release.ts
lib/export-types.ts

The previous implementation in #1624 is not defining the `release.metadata.withReferences` type as an array properly which causes errors when trying to use the type. Here I am fixing this.
The new types were also not exported from `./lib/export-types.ts`, so I am doing that here.

fix: release metadata types []

---

test/integration/entry-integration.js

Temporarily skip the x-space reference flaky test, to unblock the CI pipeline

Fix: skip x-space reference flaky test [NONE]

---

package.json

Move type-fest from dev-dependencies
it fixes https://github.com/contentful/contentful-management.js/issues/1410

fix: move type-fest from dev-dependencies

---

lib/contentful-management.ts

Changing the declaration order with having the deprecation on top fixes the issue in https://github.com/contentful/user_interface/pull/13691

fix: declare the depricated definition first to fix the import issue [HOMER-1556]

---

lib/adapters/REST/endpoints/asset.ts
lib/common-types.ts
lib/plain/common-types.ts

Allow asset.getMany method to accept extra headers.

feat: allow asset.getMany to accept extra headers

---

lib/adapters/REST/endpoints/snapshot.ts
lib/common-types.ts
lib/plain/common-types.ts

As SnapshotsAPI returns instead of three entity fields `sys`, `fields` and `metadata`  only two (except `metadata`), we need to adjust TypeScript types.
Only type changes involved, no actual behavioural changes.

fix: exclude `metadata` field from types related to SnapshotAPI

---

lib/adapters/REST/endpoints/comment.ts
lib/common-types.ts
lib/entities/comment.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/plain-client-test.ts

- chore: add comments about future refactoring (we're currently having typing issues in web app since `Document` and `RichTextDocument` collide.
- refactor: rename RichComment to RichTextComment (use the same prefix in all types)
- feat: add parent to comment type (very old "bug" that just surfaced in web app when adding types)
- refactpr: rename RichTextDocument to RichTextCommentDocument (this type is only usable for comments, so better make it clear that this is not about normal rich text fields)

fix: improve exported types for rich text comments [HOMER-1764]

---

lib/common-types.ts
lib/contentful-management.ts

We are currently streamlining adapter types by removing unnecessary parameters. Although the code below was previously valid, passing { apiAdapter: sdk.cmaAdapter } negates the need for additional parameters to be passed. Therefore, if you pass apiAdapter, no further parameters are required. Now the below code will give error.
```
const client = contentful.createClient(
{ apiAdapter: sdk.cmaAdapter, accessToken: 'YOUR_ACCESS_TOKEN' },
{ type: "plain" }
);
```
Change the `ClientOptions` to accept only one of the either `RestAdapterParams` / `AdapterParams`

fix: forbid combining REST and App adapter types in ClientOptions

---

lib/entities/workflows-changelog-entry.ts

workflow.sys.id is going to be optional for the request parameters, in order to be able to retrieve all past workflows.

feat: make workflow.sys.id optional to find all past workflows [HOMER-2006]

---

lib/entities/content-type-fields.ts

Adds types for `nodes` validation object in `ContentFields.validations`
* Changes `enabledNodeTypes` validation to only accept valid string values
* Creates a new interface NodesValidation which includes the available types for Rich Text nodes
* Adds validation type for the new `embedded-resource-block` node
* Add nodes key to the ContentTypeFieldValidation interface
The lack of a defined type makes it hard to work with RichText field validations while using Typescript and will not autocomplete the property while using javascript.
This PR supersedes #1829 and #1854 as this PR has somewhat stricter types defined and also includes the type for the `embedded-resource-block` node.

feat: add types for nodes validations

---

lib/entities/app-installation.ts

title
AppInstallations don't have an id

fix: remove `sys.id` from `AppInstallationProps`

---

lib/entities/content-type.ts
lib/export-types.ts

This PR changes the typing for `ContentfulMetaData` in order to align with new Annotations.
`AnnotationAssignment` type is added to `ContentfulMetaData`.

feat: add new annotation type [MONET-1301]

---

lib/entities/content-type-fields.ts

Allow `null` value for validation `message`
It turns out the `message` value for validations can be set to `null`. This PR updates the Typescript type to reflect this.
The Typescript type is not correct for the possible value set for `message`

fix: allow null type for validation message []

---

package-lock.json
package.json
webpack.config.js

This PR upgrades webpack and related packages to version 5.
The config changes needed are actually quite minimal:
- adjusted `node.os: 'empty'` to `resolve.fallback.os: false` as stated here https://webpack.js.org/migrate/5/#clean-up-configuration
- removed `OccurrenceOrderPlugin` as it's on by default: https://webpack.js.org/migrate/3/#occurrenceorderplugin-is-now-on-by-default
We are using the `contentful-management` library in a React app and recently upgraded our build system to use webpack 5. After this upgrade we were seeing runtime errors relating to enums from this library not being defined.
We were able to narrow down the issue to the minimization step of webpack. With `minimize: false` everything is working fine. So I decided to give upgrading to webpack 5 in this repo a try and …

Upgrade to webpack 5

---

lib/adapters/REST/endpoints/app-bundle.ts
lib/entities/app-bundle.ts
test/unit/create-app-definition-api-test.js

New EAP property for allow delivery functions upload.
App bundles will now support an extra feature - delivery functions. Sibling PR: https://github.com/contentful/create-contentful-app/pull/1641

feat(deliveryFunctions): Allow CCA to upload delivery functions [MONET-1336]

---

lib/entities/personal-access-token.ts

- Support optional `expiresIn` parameter in `CreatePersonalAccessTokenProps`.
- Support optional `expiresAt` parameter in `PersonalAccessTokenProp.sys`.
- Update 2 out-of-sync types to support new CMA access tokens TTL features.
- Test `personalAccessToken.create` and `personalAccessToken.get` methods on the plain client
- Test `createPersonalAccessToken` and `getPersonalAccessToken` methods on the default client
We are updating the client types to reflect the API changes.
In the follow up pull requests, additional changes will be introduced, moving away from Personal Access Tokens (PATs) and using new entity of unified Access Tokens (PAT, CLI, OAuth) will be introduced.
For now, though, we are just updating PAT types.

feat: support optional expiresIn param in token creation [AHOY-2470]

---

lib/adapters/REST/endpoints/app-action-call.ts
lib/common-types.ts
lib/entities/app-action-call.ts
test/unit/adapters/REST/endpoints/app-action-call-test.ts

Allows the caller to specify a `retries` and/or `retryInterval` in calls to `appActionCall.createWithResponse()`
The current `retry` and `retryInterval` values are hard coded to 10 and 2 seconds respectively. But some operations implemented with App Action can take longer than 20 seconds (for example, AI image processing).

feat: allow retry and retryInterval to be specified in appActionCall.createWithResponse [INTEG-1208]

---

lib/plain/common-types.ts
lib/plain/entities/app-action-call.ts
lib/plain/entities/app-action.ts

adds inline documentation for plain client APIs for working with App Actions and App Action Calls
we want the plain client to become the default way developers consume this SDK, so we need to provide examples for how to do that

[EXT-4731] docs: add tsdocs for plainClient app action APIs

---

lib/plain/common-types.ts
lib/plain/entities/editor-interface.ts

adds inline documentation for plain client APIs for working with Editor Interfaces
stacks on https://github.com/contentful/contentful-management.js/pull/1942
we want the plain client to become the default way developers consume this SDK, so we need to provide examples for how to do that

[EXT-4732] docs: add tsdocs for plainClient Editor Interface APIs

---

lib/plain/common-types.ts
lib/plain/entities/ui-config.ts
lib/plain/entities/user-ui-config.ts

adds inline documentation for plain client APIs for working with UI Configs and User UI Configs
stacked on https://github.com/contentful/contentful-management.js/pull/1942
we want the plain client to become the default way developers consume this SDK, so we need to provide examples for how to do that

[EXT-4733] docs: add inline TSDocs for the plain client UI Config & User UI Config APIs

---

lib/entities/content-type-fields.ts

We need to respect the legacy shape of content type validations where the field `linkContentType` can also just by a string.

fix(types): content type validation [NONE]

---

lib/plain/common-types.ts
lib/plain/entities/app-definition.ts
lib/plain/entities/editor-interface.ts
lib/plain/entities/ui-config.ts
lib/plain/entities/user-ui-config.ts

adds inline documentation for the App Definition plain client interface

docs: add inline code docs for the plain client App Definition interface [EXT-4721]

---

lib/plain/common-types.ts
lib/plain/entities/app-bundle.ts

adds inline documentation for the App Bundle plain client interface

docs: add inline docs for the plain client App Bundle interface [EXT-4723]

---

lib/plain/common-types.ts
lib/plain/entities/app-details.ts

adds inline documentation for the App Details plain client interface

docs: add inline docs for the plain client App Details interface [EXT-4724]

---

lib/adapters/REST/endpoints/environment-template.ts
lib/common-types.ts
lib/create-contentful-api.ts
lib/entities/content-type-fields.ts
test/integration/environment-template-integration.ts
test/unit/create-contentful-api-test.js

- Extends environment template `get` to accept query parameters.
- Fixes environment template `getMany` and `versions` to correctly pass cursor based pagination options as part of query params (along with including `select` in the query params).

fix(types): environment template adapter [MONET-1248]

---

lib/plain/common-types.ts

- Small fix for typings in `lib/plain/common-types.ts`

fix(types): plain client templates [MONET-1248]

---

lib/plain/common-types.ts
lib/plain/entities/app-action.ts
lib/plain/entities/app-bundle.ts
lib/plain/entities/app-details.ts
lib/plain/entities/app-installation.ts
lib/plain/entities/app-upload.ts

adds inline documentation for the App Installation plain client interface

docs: add inline docs for the plain client App Installation interface [EXT-4729]

---

lib/plain/common-types.ts
lib/plain/entities/webhook.ts

adds inline documentation for the Webhook plain client interface

docs: add inline docs for the plain client Webhook interface [EXT-4720]

---

lib/create-environment-api.ts
lib/create-space-api.ts
lib/plain/common-types.ts
lib/plain/entities/app-action-call.ts
lib/plain/entities/app-signed-request.ts
lib/plain/entities/app-signing-secret.ts

adds inline documentation for the App Signing Secret and Signed Request plain client interfaces

docs: add inline docs for the plain client App Signed Request and Signing Secret interface [EXT-4726]

---

lib/plain/common-types.ts
lib/plain/entities/extension.ts

adds inline documentation for the UI Extension plain client interfaces

docs: add inline docs for the plain client UI Extensions [EXT-4719]

---

lib/entities/content-type-fields.ts

We realised that the change introduced with [this](https://github.com/contentful/contentful-management.js/pull/1966) is causing same trouble.  After reviewing it again we decided to revert the change.

fix(types): revert content type field validation change [NONE]

---

.circleci/config.yml

We currently don't want to create releases from branches other than `master`

chore: remove non-master releases [NONE]

---

lib/adapters/REST/endpoints/app-event-subscription.ts
lib/adapters/REST/endpoints/app-key.ts
lib/adapters/REST/endpoints/index.ts
lib/common-types.ts
lib/create-organization-api.ts
lib/entities/app-event-subscription.ts
lib/entities/app-key.ts
lib/entities/index.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/entities/app-event-subscription.ts
lib/plain/entities/app-key.ts
lib/plain/plain-client.ts
test/integration/app-event-subscription-integration.js
test/integration/app-key-integration.js
test/unit/create-organization-api-test.js
test/unit/entities/app-event-subscription-test.ts
test/unit/entities/app-key-test.ts
test/unit/mocks/entities.js

Adds the `upsert`, `get`, and `delete` client methods for AppEventSubscriptions, and the `create`, `get`, `getMany` and `delete` client methods for AppKeys
CMA JS client <-> API feature parity

feat: add client methods for AppEventSubscriptions and AppKeys [EXT-4755] [EXT-4757]

---

lib/entities/app-key.ts
test/integration/app-key-integration.js

Updates AppKeyProps to reflect that the generated private key is returned alongside the JWK.
This is a followup to https://github.com/contentful/contentful-management.js/pull/2011
The [default-values-backend example app](https://github.com/contentful/apps/tree/master/examples/default-values-backend) is using this functionality.

fix: return private key if generate is enabled during app key creation [EXT-4757]

---

lib/entities/app-definition.ts

We are adding installation parameter schemas to the app definition
We need to update this here so we can reference the installation property in User Interface
App creators have to currently use the frontend to validate user's installation params. This will allow them to offload most of that logic to our backend when the user saves

feat: add installation param schema to app definition INTEG-1385

---

lib/adapters/REST/endpoints/comment.ts
lib/common-types.ts
lib/entities/comment.ts
lib/plain/plain-client-test.ts
test/integration/comment-integration.ts

Follow-up of https://github.com/contentful/contentful-management.js/pull/2023
* You can create replies by passing `parentCommentId`
* You can add a parent entity reference by passing `parentEntityReference`
* Types for deletion and updating now support content types and workflows
* Add `status` type
* Allow filtering by `status`
Do we want to deprecate the old `{ entryId: string }` syntax for creating comments?

feat: fix comment types & support parentEntityReference, replies & status

---

lib/adapters/REST/endpoints/webhook.ts
lib/common-types.ts
lib/create-space-api.ts
lib/entities/webhook.ts
lib/export-types.ts
lib/plain/entities/webhook.ts
lib/plain/plain-client.ts
test/unit/plain/webhook-test.ts

Adds plain client methods for fetching, upserting, and deleting webhook signing secrets.

feat: add webhook signing secrets to legacy and plain client interfaces [EXT-4817]

---

.circleci/config.yml
package.json

Since version `10.27.1` we are not baking in the right version anymore. The problem must have been introduced with [these](https://github.com/contentful/contentful-management.js/compare/v10.27.0...v10.27.1) changes.  
With the first commit, we added a new test script `npm run test:version` to check for the occurrence of `0.0.0-determined-by-semantic-release` in the build output ([example run](https://app.circleci.com/pipelines/github/contentful/contentful-management.js/8958/workflows/23ff7b85-1afd-4c01-a2e3-4468bbd4800a/jobs/27465)) 
In a second step, we execute the build step and the version test **AFTER** `npm` already set the right version in the package.json be using npm's the lifecycle hook `prepublishOnly`.  (similar to what we do for …

fix: add test step for relase version [NONE]

---

lib/adapters/REST/endpoints/upload.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/upload.ts
test/integration/asset-integration.js
test/unit/adapters/REST/endpoints/upload-test.js

Somewhat recently there was a CEP for updating the upload-api that was approved and a subsequent PR that was merged. This effectively means the Upload API now takes in both the Environment Id and Space Id for a given request.

fix: update createUpload to accept environment id in its params [INTEG-1492]

---

lib/adapters/REST/endpoints/app-action-call.ts
test/unit/adapters/REST/endpoints/app-action-call-test.ts

Extends the retry duration when using `AppActionCall.createWithResponse` to 30 seconds (15 retries with a 2 second retry interval.
Today, createWithResponse retries only 10 times with a 2s interval, which works out to about 20 seconds. We just extend the polling here to 30 seconds.
Long running hosted app actions can take longer than 20 seconds. We are discovering that AI image manipulation frequently takes 20-25 seconds.

fix: retry AppActionCall for up to 30s [INTEG-1208]

---

package-lock.json
package.json

See: https://github.com/contentful/contentful-management.js/issues/2054
Upgrade axios to latest available version
Using contentful-management introduces a vulnerable transitive dependency into any user that uses this library. This fix will mitigate this.

[fix] Update axios to 1.6.2 to remove vulnerabilities

---

lib/adapters/REST/endpoints/asset.ts
lib/adapters/REST/endpoints/upload.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/upload.ts
lib/plain/common-types.ts
test/integration/asset-integration.js
test/integration/webhook-integration.js
test/unit/adapters/REST/endpoints/upload-test.js
test/unit/entities/upload-test.js

(Re)introduce environment scoped uploads.
This PR restores environment scope uploads that were introduced here https://github.com/contentful/contentful-management.js/pull/2030 and reverted here https://github.com/contentful/contentful-management.js/pull/2084 
The issue with the original PR was raised here https://github.com/contentful/contentful-management.js/issues/2075 . Further investigation revealed that the problem was in fact an issue with the backend asset processing service. This service was missing a key piece of logic to make it aware that the upload passed for processing could be in a specific environment instead of at the space level. The SDK change revealed that backend issue when it exposed environment scoping to uploads.

fix: environment-scoped uploads

---

lib/entities/upload.ts

* Include environment as optional parameter in `UploadProps`
In https://github.com/contentful/contentful-management.js/pull/2088 we added support for environment-scoped uploads. When an environment id is provided, the upload created is scoped to that environment. When no environment is created, the upload remains at the space level.
We overlooked one type change, however, which is that the `Upload` object returned from the API will have the environment link in the sys if it has been explicitly environment scoped.

fix: add environment to upload props

---

lib/methods/content-type.ts
test/integration/content-type-integration.js

Fix content type omitAndDelete function
Turned out that if a field is published the omitted step also needs to be published in order to delete the field finally.
Customers are reporting that this function doesn't work under certain circumstances.

fix: omitAndDelete function [PHX-2612]

---

lib/adapters/REST/endpoints/role.ts
lib/common-types.ts
lib/create-organization-api.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/role-integration.js

Add method to query all roles of an organization (`/organization/:orgId/roles`)
Plain: `client.roles.getManyForOrganization(...)`
Nested: `organization.getRoles(...)`

feat: add `getRoles` for organization [CFCX-1226]

---

lib/adapters/REST/endpoints/space.ts
lib/common-types.ts
lib/create-organization-api.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/space-integration.js

Adds `client.spaces.getManyForOrganization` (plain) and `organization.getSpaces()` (nested)
Required for requests in the Web App
Currently, only the `/spaces` endpoint is implemented. It's not possible to query the spaces of a specific org.

feat: add `getSpaces` for organization

---

lib/adapters/REST/endpoints/asset.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/asset-integration.ts

The GET endpoint for published assets was not yet added to the client.
https://www.contentful.com/developers/docs/references/content-management-api/#/reference/assets/published-assets-collection (JavaScript)

feat: add support for GET published asset endpoint []

---

lib/adapters/REST/endpoints/app-bundle.ts
lib/entities/app-bundle.ts
test/unit/create-app-definition-api-test.js

This PR renames delivery functions to functions. 
[Ticket](https://contentful.atlassian.net/browse/MONET-1733)
Delivery functions is a feature is EAP and it is currently being renamed to Functions. This PR updates the client to be later used in `create-contentful-app` repository.

refactor: rename delivery functions to functions [MONET-1733]

---

lib/common-types.ts

Introduce `ResourceLink` type for resource links which have been used for [cross-space references](https://www.contentful.com/help/cross-space-references/) for a while.
This package is the source of truth for types for multiple other projects. Some already define `ResourceLink` on their own while others need it soon so it’s better to have it in one place.

feat: add ResourceLink type

---

lib/entities/app-bundle.ts
lib/entities/function.ts

[Ticket](https://contentful.atlassian.net/browse/MONET-1825)
This PR adds `accepts` as an optional parameter to `appBundle` and `function` props.

feat: add accepts as an optional parameter [MONET-1825]

---

lib/adapters/REST/rest-adapter.ts
lib/contentful-management.ts
lib/create-adapter.ts

A single `axios` instance allows for [stateful adapters](https://github.com/contentful/contentful-sdk-core/pull/214). there is technically also no need to create an instance for every call. 
We create a `axiosInstance` calls member to the RestAdapter, and pass it in to the endpoint function.

feat: use a single axios instance [PHX-2863]

---

lib/plain/common-types.ts
lib/plain/entities/locale.ts

docs for locale operations on the plain client interface

docs: add TSDocs for the locale entity on the plain client interface

---

lib/plain/entities/locale.ts

We recently added inline documentation for the Locale plain client interface, this changeset includes a tiny tweak to the locale.getMany inline example

docs: fix inline doc example for the plain client locale getMany method [EXT-4965]

---

lib/plain/common-types.ts
lib/plain/entities/tag.ts

adds inline documentation for the Tag plain client interface

docs: add inline docs for the plain client Tag interface [EXT-4966]

---

test/integration/asset-integration.ts

skipping this test for now so we can release [this fix](https://github.com/contentful/contentful-management.js/pull/2194)

fix: skip flaky asset API integration test

---

lib/adapters/REST/endpoints/app-access-token.ts
lib/adapters/REST/endpoints/index.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/app-access-token.ts
lib/entities/index.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/entities/app-access-token.ts
lib/plain/plain-client.ts
package-lock.json
package.json
test/integration/app-access-token-integration.js
test/unit/create-environment-api-test.js
test/unit/entities/app-access-token.ts
test/unit/mocks/entities.js

Adds the `create` client method for AppAccessTokens
CMA JS client <-> API feature parity

feat: add client methods for AppAccessTokens [EXT-4754]

---

lib/adapters/REST/endpoints/webhook.ts
lib/plain/entities/webhook.ts

Deprecates methods for interacting with the custom Webhook Retry Policy API.  The EAP for this feature has ended and the endpoints will no longer work.

feat: deprecate webhook retry policy methods [EXT-5117]

---

lib/entities/workflow-definition.ts
lib/export-types.ts

This PR changes the export of 3 enums that are needed in the workflow-management-api and workflows-marketplace-app as normal types, since they were exported before as `export type ... ` it was not possible to access their values

feat: export enum values for WorkflowStepPermission* types [CFISO-1367]

---

.circleci/config.yml

Our 3 core packages, contentful.js, contentful-management.js and contentful-sdk-core all differ in the way they store and lock dependencies.
This is one of 3 PRs that will align that behavior:
* Migrate from yarn to npm
* Ensure lock file is committed to repository, but not included in package releases
* Ensure CircleCI uses modern, recommended way by CircleCI to install packages
* Ensure CircleCI uses the latest minor version of our minimum node version
Related PRs:
* https://github.com/contentful/contentful.js/pull/2164
* https://github.com/contentful/contentful-sdk-core/pull/440

refactor: normalize package managers & CircleCI

---

lib/entities/field-type.ts

Correct typing of arrays containing resource link items
The typings exposed for arrays containing resource link items appear to be incorrect, using the casing `Resourcelink` where all other documentation and examples capitalise the `l` like `ResourceLink`

fix(entities/field-type): correct casing of resourcelink array item types

---

lib/entities/app-definition.ts
lib/entities/extension.ts
lib/entities/widget-parameters.ts
lib/export-types.ts
test/integration/app-definition-integration.js
test/unit/mocks/entities.js

When creating App Installation Parameter schemas by modifying an App Definition, users can now specify that a parameter is of type "Secret". At the time of this PR this functionality is currently only supported on the schema side. 
Apps will soon be able to use secret app installation parameters for storing params whose exposure should be limited.
Documentation updates to come as this feature matures.

feat: Add new App Installation Parameter value type 'Secret' [EXT-4836]

---

lib/common-types.ts
lib/entities/content-type.ts
lib/entities/entry.ts

Adds taxonomy validations to metadata object
Adds Concept assignment object to
This is the first step of bringing taxonomy data to the management client. IN a follow up PR we will introduce the management functionality for taxonomy
Docs: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/taxonomy

feat: adds taxonomy validation and assignmnt [GROOT-1263]

---

.github/dependabot.yml
package-lock.json
package.json

We're not yet certain that axios 1.7.x is compatible with the underlying [contentful-sdk-core](https://github.com/contentful/contentful-sdk-core) library that this SDK depends on. We'll upgrade to that version manually when we're more certain about that. In the mean time, this change will prevent Dependabot from making that upgrade for us.

fix: pin axios to 1.6.x

---

lib/entities/widget-parameters.ts
lib/export-types.ts

`ParameterType` and `ParameterOption` should be exported from `entities/widget-parameters` so they can be used in other codebases without duplication.

fix: export ParameterType and ParameterOption [EXT-5252]

---

lib/contentful-management.ts
lib/plain/pagination-helper.ts
test/unit/plain/pagination-helper-test.ts

We plastered a few versions of this behaviour in Contentful internal packages, so clearly there is a need for it. This is why we want to start having a single source of truth for it.
The introduced `fetchAll` method can handle offset-based and cursor-based endpoints by inspecting the initial response.
We have one caveat though: As we have inconsistent ways of handling how we pass down optional query parameters (sometimes as distinct `query` property, sometimes mingled with mandatory properties). I opted for the more explicit version of using a distinct property. In case there is a need downstream the endpoint method that can't be handled automatically simply need to be wrapped.
An example for the raw.get method looks like this:
```typescript
const items = await fetchAll(({ query }) => …
```

feat: add `fetchAll` convenience method on top of paginated endpoints

---

.circleci/config.yml

The `json` package is used by `contentful-sdk-jsdoc` here: https://github.com/contentful/contentful-sdk-jsdoc/blob/master/bin/publish-docs.sh#L15, so we need to make sure it is installed prior to running the release step

fix: ensure json is installed globally before running semantic-release []

---

lib/plain/pagination-helper.ts

As mentioned in the code, we loosely type `sys.type` of collections in our App SDK as string and therefore have problems using the convenience helper.

fix: omit `sys` type property in fetchAll helper

---

test/integration/app-access-token-integration.js

JWT.sign is not guaranteed to be an exact length, so we need to give it some wiggle room.

chore: improve token length check in app-access-token-integration test

---

test/integration/taxonomy-integration.ts

Temporarily disable the taxonomy integration tests to unblock others. We will look into this later today

fix(taxonomy): disable taxonomy integration test [NONE]

---

package-lock.json

To fix the https://github.com/advisories/GHSA-8hc4-vh64-cxmj vulnerability.

build(deps): bump axios from 1.7.3 to 1.7.4

---

lib/constants/editor-interface-defaults/controls-defaults.ts

Default widget namespace is misspelled as `widgetNameSpace` instead of `widgetNamespace`. 
Integration tests are failing for something irrelevant (affects all open PRs)

fix(editor-defaults): typo in widget namespace attribute

---

lib/adapters/REST/endpoints/index.ts
lib/adapters/REST/endpoints/resource-type.ts
lib/common-types.ts
lib/entities/index.ts
lib/entities/resource-provider.ts
lib/entities/resource-type.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/entities/resource-type.ts
lib/plain/plain-client.ts
test/integration/resource-provider-integration.ts
test/integration/resource-type-integration.ts
test/unit/entities/resource-provider-test.ts
test/unit/entities/resource-type-test.ts
test/unit/mocks/entities.js
test/unit/plain/resource-type-test.ts

Add Resource Type for Native External References

feat: add Resource Type to contentful-management [DANTE-1832]

---

lib/adapters/REST/endpoints/access-token.ts
lib/adapters/REST/endpoints/organization.ts
lib/adapters/REST/endpoints/personal-access-token.ts
lib/common-types.ts
lib/create-contentful-api.ts
lib/create-organization-api.ts
lib/entities/access-token.ts
lib/entities/organization.ts
lib/entities/personal-access-token.ts
lib/entities/release-action.ts
lib/entities/scheduled-action.ts
lib/export-types.ts
lib/plain/common-types.ts
lib/plain/entities/organization.ts

While rewriting and typing tests to vitest, I found out that some types are not reflecting the actual Contentful API structure. 
https://github.com/contentful/contentful-management.js/pull/2328
* Ensure all prop interfaces are plural
* `AccessTokenProp` -> `AccessTokenProps`
* `PersonalAccessTokenProp` -> `OrganizationProps`
* `OrganizationProp` -> `OrganizationProps`
* `EntityMetaSysProps`
* Removed `contentType` (As its entry only)
* Added `status?` (Some entity have it)
* `EntryMetaSysProps`
* Added `contentType` (As assets & co don't have this prop -> https://www.contentful.com/developers/docs/references/content-management-api/#/reference/assets/asset)
* `ReleaseActionSysProps`
* Added `updatedBy` (https://www.contentful.com/developers/docs/references/content-management-api/#/reference …

fix: align types to API and normalize naming

---

test/integration/asset-integration.ts
test/integration/entry-integration.ts

Additional test coverage for assigning concepts to Assets and Entries.
Covers 3 main areas:
1. Creating an {entry/asset} with a new concept assigned
2. Updating an {entry/asset} with a new concept assigned
3. Deleting an assigned concept from an {entry/asset}
As per summary, but also migrated `entry-integration.js` to Typescript.
The implementation was already functionally in place to assign a Concept to a Taxonomy, therefore this PR is just for some additional test coverage.

test: [GROOT-1483] New integration tests for Taxonomy Assets and Entries

---

lib/create-environment-api.ts
test/integration/locale-integration.js

Looks like locals only support max page size of 100.  So, if an env has more than 100 we cannot fetch them all using contentful-management

feat: allow locales to be paginated [ZEND-5557]

---

lib/entities/upload-credential.ts
lib/export-types.ts

we were not exporting the types for the new upload credentials method. Our example for how to use the method was also out of date. This should be fixed now

chore: fix types & docs for upload credentials []

---

package-lock.json
package.json

Explicitly upgrade axios so downstream consumers know that the latest is the acceptable valid version. 
- Explicitly upgrade axios to ^1.7.9
- Run `npm audit fix` to resolve 3 moderate vulns
Even though axios was bumped to 1.7.9 in the lockfile here https://github.com/contentful/contentful-management.js/pull/2493, 1.7.4 was still marked as valid for downstream consumers, so they wouldn't get the new version without regenerating their lockfile or executing `npm audit fix` in their projects that use contentful-management.

fix: upgrade axios to 1.7.9 [ZEND-5779]

---

lib/plain/entities/app-installation.ts

This changes adds partially missing types to align with the types defined [here](https://github.com/contentful/contentful-management.js/blob/master/lib/adapters/REST/endpoints/app-installation.ts). 
This allows for querying app installations by `spaceId`.

fix: app installation parameter types [NONE]

---

lib/plain/wrappers/wrap.test-d.ts
lib/plain/wrappers/wrap.ts

Fix `params` arguments of some plain client methods
The updated `OptionalDefaults` type introduced in https://github.com/contentful/contentful-management.js/pull/2491 causes issues for intersection types combined with union types.
This makes some plain client methods unusable
The issue is that the builtin `Omit` doesn't play well with intersections. This PR replaces that with a union-compatible `Omit`

fix: plain client method argument types for `params` with intersection types

---

lib/adapters/REST/endpoints/asset.ts
lib/adapters/REST/endpoints/entry.ts
lib/common-types.ts
lib/plain/common-types.ts

Add extra param for passing locales to singular entity publish/unpublish method.
We are not adding this functionality to old (nested) client as it is soon to be deprecated.
With recent release of locale-based publishing, we add this functionality to public client. Adding `locales` param to publish/unpublish endpoints.
Aligning with recent release of Locale-based publishing.

feat: [] Locale-based publish support in CMA client

---

lib/entities/app-installation.ts

Adding `sys.organization` as a property to app installations.
Make public types consistent with the adjusted payload.

feat: add `sys.organization` property to `AppInstallation` entity

---

lib/adapters/REST/make-request.ts
lib/adapters/REST/rest-adapter.ts
lib/contentful-management.ts

Extract make request to make adapter creation easier
Serverless execution environments will benefit from using an adapter that uses native fetch rather than axios.  This exports the helper makeRequest so we don't have to implement the entire interface

feat: export make request [EXT-6172]

---

.circleci/config.yml
eslint.config.mjs
package-lock.json
package.json
test/output-integration/browser/.gitignore
test/output-integration/browser/README.md
test/output-integration/browser/package-lock.json
test/output-integration/browser/package.json
test/output-integration/browser/public/index.html
test/output-integration/browser/public/index.js
test/output-integration/browser/scripts/inject-env.js
test/output-integration/browser/test/index.test.js
test/output-integration/browser/vitest.config.ts
test/output-integration/browser/vitest.setup.ts
test/output-integration/node/README.md
test/output-integration/node/index.test.ts
test/output-integration/node/package-lock.json
test/output-integration/node/package.json
vitest.workspace.js

This is part of #2472 and could be extracted to simplify review :)
Its not a breaking change, when its green, we can add it and will have two security measurements more to make sure our API client works in all environments.

test: quick node and browser e2e test after build

---

lib/entities/app-action.ts
lib/plain/entities/app-action.ts

App Action types did not have the correct properties for `function-invocation`. This PR corrects that, makes the types more specific for each of the app action types, and also updates the examples for create and update to show how to do it for an app action that targets a function.
Create base app action and type-specific types for endpoint, function-invocation, and function (deprecated) app actions. 

fix: update app action types to support function-invocation [EXT-5873]

---

lib/common-types.ts
lib/create-environment-api.ts
lib/plain/entities/function-log.ts

Function logs can now be queried by interval, using either Date objects or ISO strings
For example:
```typescript
const timeStart = new Date()
const timeEnd = new Date()
timeEnd.setHours(then.getHours() - 1)
// Plain Client:
const functionLogs = await plainClient.functionLogs.getMany({
spaceId: '<space_id>',
environmentId: '<environment_id>',
appInstallationId: '<app_installation_id>',
functionId: '<function_id>',
query: {
'sys.createdAt[gte]': timeStart,
'sys.createdAt[lt]': timeEnd
}
})
// Legacy client:
client.getSpace('<space_id>')
.then((space) => space.getEnvironment('<environment_id>'))
.then((environment) =>
environment.getFunctionLogs(
'<app_installation_id>',
'<function_id>',
{
query: {
'sys.createdAt[gte]': new Date("2025-03-03T16:29:15.165Z"),
'sys.createdAt[lt]': …
```

feat: allow function logs to be queried by interval [EXT-6221]

---

lib/plain/common-types.ts

Adding missing `version` param to the plain client entry patch params
`client.entry.patch` expects `version` to be passed in, however `version` is currently not included in the TypeScript types.

fix: add `version` param to patch method of plain client

---

lib/entities/app-event-subscription.ts
lib/plain/entities/app-event-subscription.ts

App Event Subscription types did not include the `functions` property that is needed to add a filter, transformation, or handler function to a subscription.
This PR adds a `functions` property to the `AppEventSubscriptionProps` type. This property accepts 3 different types of function links: filter, transformation, and handler. I also made the `targetUrl` property optional, because you can have an app event subscription that targets a handler function instead of a url. Finally, I updated the comments for the upsert function to show examples of targeting a url vs. targeting a function. I tested these changes in a script where I am upserting app event subscriptions that contain functions.
This change will make it easier for developers looking to use App Event Functions.
When adding a new …

fix: update app event subscription to support functions [EXT-6289]

---

lib/adapters/REST/endpoints/ai-action.ts
lib/common-types.ts
lib/create-space-api.ts
lib/entities/ai-action.ts
lib/plain/entities/ai-action.ts
test/integration/ai-action-integration.test.ts
test/integration/ai-action-invocation-integration.test.ts
test/unit/create-space-api.test.ts

[Ticket](https://contentful.atlassian.net/browse/BBEE-1154)
Ai action publish method should be called as following:  `client.publishAiAction('space_id', { version: 4 })`
We are not passing a payload to the publish function anymore. 
Space client call:
```
const space = await legacyClient.getSpace(process.env.SPACE_ID);
const res =  await space.getAiAction(process.env.AI_ACTION_ID);
const result = await space.publishAiAction(process.env.AI_ACTION_ID, {
version: 4,
});
```
Legacy client call:
```
const currentAction = await plainClient.aiAction.get({
spaceId: process.env.SPACE_ID,
aiActionId: process.env.AI_ACTION_ID,
});
const result = await plainClient.aiAction.publish(
{
spaceId: process.env.SPACE_ID,
aiActionId: process.env.AI_ACTION_ID,
version: 2
},
);
```

feat: client.publish payload

---

lib/entities/app-bundle.ts

Since adding Contentful Functions as a capability, the `AppBundle` entity can now contain an optional `functions` property. This PR updates the `AppBundleProps` type to reflect this.
Added optional `functions` property to the `AppBundleProps` type. This property is an array of `FunctionManifestProps`. Note that the `CreateAppBundleProps` type already supports an optional `functions` property.

feat: add optional functions property to AppBundleProps type [EXT-6304]

---

lib/plain/common-types.ts

As a follow up to this PR (https://github.com/contentful/contentful-management.js/pull/2547), we are making the `version` param for patch in the plain client optional again, since this caused some issues to customer code when updating to a new CMA version that included this change. We will re-introduce this as a required param in the next major release.

fix: make version param optional in patch method [DX-34]

---

lib/plain/common-types.ts

As a follow up to this PR (https://github.com/contentful/contentful-management.js/pull/2609) we are making the version param required for the entry patch method of the plain client. 
`client.entry.patch` expects version to be passed in, however `version` is currently not included in the TypeScript types. This param was made optional, and now we are making this required. This will be released as a breaking change in CMA.js v12.
- ✅ Both unit and integration tests are passing
- ❌ There are no breaking changes
- ✅ Changes are reflected in the documentation

fix: make version param required for entry patch method of plain client [DX-34]

---

lib/export-types.ts
package-lock.json
package.json

- Merge changes from master into beta and fix conflicts in package-lock.json
- Remove old file name from `size-limit` in package.json
- Export additional types from entities
Test these changes on our beta branch

fix: export additional types and remove old file from size-limit [DX-4]

---

lib/entities/environment-template.ts
test/integration/environment-template-integration.test.ts

Add the new optional `forTemplatedSpaces` property for creating and editing environment templates.
Add the new optional `forTemplatedSpaces` property for creating and editing environment templates to the `EnvironmentTemplateProps` type. Also update the environment template creation helper in the integrations tests with this new property.

feat: add forTemplatedSpaces property for env template operations [DX-173]

---

lib/plain/wrappers/wrap.ts
test/unit/contentful-management.test.ts

Add `releaseId` as a default initialization param.
See (internal only) [RFC](https://contentful.atlassian.net/wiki/spaces/PROD/pages/5125242881/SDK+API+Campaign+Context+Specifics) for detail
https://contentful.atlassian.net/browse/DX-185

feat(default): release-id

---

test/defaults.ts
test/integration/entry-integration.test.ts
test/integration/entry-references-integration.test.ts

Created new Entries that seem to have been inadvertently deleted and updated the const file with the new ids

chore: update test entry IDs in TestDefaults for failing integ tests [DX-198]

---

lib/entities/environment-template.ts
test/defaults.ts
test/helpers.ts
test/integration/app-access-token-integration.test.ts
test/integration/app-action-integration.test.ts
test/integration/app-bundle-integration.test.ts
test/integration/app-definition-integration.test.ts
test/integration/app-details-integration.test.ts
test/integration/app-event-subscription-integration.test.ts
test/integration/app-key-integration.test.ts
test/integration/app-signed-request-integration.test.ts
test/integration/app-signing-secret-integration.test.ts
test/integration/app-upload-integration.test.ts
test/integration/bulk-action-integration.test.ts
test/integration/entry-integration.test.ts
test/integration/entry-references-integration.test.ts
test/integration/environment-template-integration.test.ts
test/unit/plain/resource-provider.test.ts
test/unit/plain/resource-type.test.ts
test/unit/plain/resource.test.ts
test/unit/plain/webhook.test.ts

Fix some imports (`/lib` -> `lib/index.js`) that were causing unit tests to fail and merge in the latest from master so that the integration tests will pass.

fix: update lib/index.js imports and merge in test fixes [DX-4]

---

lib/adapters/REST/endpoints/release-entry.ts
lib/common-types.ts
lib/plain/common-types.ts
lib/plain/plain-client.ts
test/integration/releasev2-integration.test.ts
test/unit/adapters/REST/endpoints/release-entry.test.ts

Add support for `client.release.entry.getMany()`.  Calls the endpoint: `/spaces/${params.spaceId}/environments/${params.environmentId}/releases/${params.releaseId}/entries`

[DX-193] feat(releases): release.entry.getMany()

---

lib/common-types.ts
lib/entities/ai-action-invocation.ts
lib/entities/ai-action.ts

- Use `AiActionQueryOptions` for nested client implementation of `AiAction.getMany`
- Convert `InvocationStatus`, `InvocationResultType`, `VariableType` and `StatusFilter` from enums to string types to improve compatibility (no requirement to import them)
- Use `Link<'User'> | Link<'AppDefinition'>` for subject links in `AiActionProps`

fix: removed inapplicable query params and improved AiAction types

---

test/integration/entry-integration.test.ts

Our releases integration tests weren't deleting one of the created entries, so that was starting to pile up in our testing space.
Ensure that both entries are deleted add the end of the test. I validated that the entry was no longer in the space after the latest CI run on this branch.

fix: delete entry2 as part of entry integration test cleanup [DX-258]

---

.circleci/config.yml
README.md
package.json

This PR will build a canary (experiemental) release and publish it under the canary tag to npm.
I took the direction of keeping this task simple and adding it to the release/releasev2 branch for now, which is where all the current experimental work is. 
If we continue to do canary releases, we should create a new canary branch, and figure out the branching/merging strategy there to keep it up to date and have multiple experiemental features in it.

chore: add canary build to release/releasev2 branch [DX-212]

---

lib/adapters/REST/endpoints/entry.ts
lib/common-types.ts
lib/plain/common-types.ts
test/integration/entry-integration.test.ts
test/unit/adapters/REST/endpoints/entry.test.ts

JIRA: [DX-210](https://contentful.atlassian.net/browse/DX-210)
`entry.update` takes `releaseId` and delegates to release entry update endpoint.
- Add `releaseId` to entry.update params
- If request has `releaseId`, call `release.entry.update` endpoint
- Unit tests for entry.update
- Integration tests for entry.update
[DX-210]: https://contentful.atlassian.net/browse/DX-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: entry.update supports releaseId [DX-210]

---

lib/adapters/REST/endpoints/app-action-call.ts
lib/common-types.ts
lib/create-environment-api.ts
lib/entities/app-action-call.ts
lib/export-types.ts
lib/plain/entities/app-action-call.ts
lib/plain/plain-client.ts
test/integration/app-action-call-structured-integration.test.ts
test/unit/adapters/REST/endpoints/app-action-call.test.ts
test/unit/create-environment-api.test.ts

Add structured App Action Call support and a convenient polling-abstracting method:
- New REST endpoints: `get` (structured call), `getResponse` (raw response), `createWithResult` (create + poll).
- Plain client API exposure with JSDocs for the new structured/response flows.
- Default client methods added for structured flow and raw response.
- Types updated to model status/result/error per RFC.
- Unit and integration tests for success, timeout, failure, transient error and endpoint paths.
- Extend `AppActionCallProps` with:
- `status: 'processing' | 'succeeded' | 'failed'`
- `result?: unknown`
- `error?: { sys: { type: 'Error'; id: string }, message: string, details?: Record<string, unknown>, statusCode?: number }`
- Extend `AppActionCallSys` with `appActionCallResponse?: SysLink`.
- Add …

feat: add new endpoints for AppActionCall to fetch structured results [EXT-6593]

---

lib/entities/app-action.ts
test/unit/adapters/REST/endpoints/app-action.test.ts

This PR extends the AppAction type definitions by introducing two new optional properties:
`resultSchema` – a JSON Schema describing the expected structure of the value returned by an App Action.
`parametersSchema` – a JSON Schema describing the expected input parameters when calling an App Action.
These additions make it easier for developers to understand, validate, and work with App Actions in a consistent and predictable way.
App Actions currently lack a standardized way to describe their input and output data. This makes it difficult for consumers to reliably use App Actions in workflows, automations, and other integrations that depend on structured results.
By adding `resultSchema` and `parametersSchema`, we provide:
- Better validation: SDKs and tooling can check that inputs and …

feat: add `resultSchema` and `parametersSchema` support to AppAction definitions [EXT-6739]

---

lib/entities/app-action-call.ts
test/unit/adapters/REST/endpoints/app-action-call.test.ts

Fix legacy client (entity wrapper) for App Action Call to accept caller-provided params/payload. The plain client was already correctly wired and is unaffected.
- Legacy client: Updated `lib/entities/app-action-call.ts` to forward caller `params` and `payload` instead of using static placeholders.
- `createWithResponse(params, payload)`
- `getCallDetails(params)`
- `get(params)`
- `createWithResult(params, payload)`
- Uses `CreateWithResponseParams`, `CreateWithResultParams`, `GetAppActionCallDetailsParams`, `GetAppActionCallParamsWithId`.
- Tests: Updated `test/unit/adapters/REST/endpoints/app-action-call.test.ts` to pass explicit `params`/`payload` to the entity methods.
- Plain client: No changes. It already used `wrap(...)` to merge defaults with user `params` and call the REST …

fix: app action call params/payload plumbing for legacy client [EXT-6763]

---

lib/create-contentful-api.ts
lib/create-organization-api.ts
lib/plain/common-types.ts
test/integration/environment-template-integration.test.ts

Align with new API capability to filter template collections by field `forTemplatedSpaces`
Follow-up to https://github.com/contentful/contentful-management.js/pull/2753

feat(environment-templates): add forTemplatedSpaces query param [FUS-958]

---

lib/adapters/REST/endpoints/release-asset.ts

Invalid query is created for release.asset.getMany as it adds the schemaVersion

fix(release-asset): invalid query for getMany []

---

lib/adapters/REST/endpoints/app-action-call.ts
lib/entities/app-action-call.ts
test/unit/adapters/REST/endpoints/app-action-call.test.ts

- Move status, result, and error fields under sys for AppActionCall
- Update polling logic and tests to check sys.status instead of top-level fields
- Extend raw response props to include createdBy
- Refactored AppActionCall entity to align with Contentful conventions: fields that are system-controlled live inside sys
- Updated pollStructuredAppActionCall to resolve based on sys.status values (succeeded, failed, processing)
- Adjusted unit tests accordingly to mock sys.status, sys.result, and sys.error
- Cleaned up redundant top-level fields 
- Ensures consistency with how other system-managed fields are represented in Contentful entities
- Reduces risk of user confusion by preventing direct mutation of system-controlled properties
- Brings App Action Call entity and polling behavior in …

fix: move app-action-call status, result, and error to sys [EXT-6783]

---

package-lock.json
package.json

Bump axios to 1.12.2 to address security vuln
Addresses concern first notified in contentful.js that also uses axios: https://github.com/contentful/contentful.js/issues/2567

fix: bump axios to 1.12.2 [DX-430]

---

lib/plain/common-types.ts

Update `processForLocale` and `processForAllLocales` param types for release assets. 
Previously, `asset` and `locale` properties were passed in both the `params` property and as their own parameters. This removes the `asset` and `locale` properties from the `params` parameter for these methods. This aligns with these methods for asset processing ([see here](https://github.com/contentful/contentful-management.js/blob/master/lib/plain/common-types.ts#L399-L409)).

fix: update params type for release asset process methods [DX-443]
